### ISSUE TITLE
I can not see youtube videos fullscreen.

### ISSUE THREAD

**Issue by jedr93** [OtterBrowser/otter-browser#1004]
Good morning, I just install "otter browser" in arch linux install otter but I cannot see video in full screen,¿ even not supported in "otter browser" full screen video.?

**Comment by Emdek** [comment]
@jedr93, QtWebKit doesn't support that.
You can try QtWebEngine backend (#615) if you have Qt 5.5 installed (and of course QtWebEngine itself too ;-)), but note that is is currently partially broken and doesn't expose all needed features due to upstream limitations (some of them will be addressed in upcoming Qt 5.6).
