### ISSUE TITLE
Weird tab switching behaviour

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1016]
When switching to a tab B from a tab A with Ctrl+tab (and just releasing the tab key to avoid looping through opened tabs) and again switching exactly the same way, I get back to A. So, I end up to do tab A, tab B, tab A, tab B, etc. and it is impossible to access other tabs the same way as we do with other browsers. (Might be related to #966.)

When switching the position of tabs, the title of the moving tab vanishes. In fact, not only the title that disappear, but also the border and the background of the tab leaving only the favicon and the close button. However, this is far less important as the two first points .

**Comment by komoku** [comment]
I guess it's the same problem that happens with the ActivatePreviouslyUsedTab action (last two comments of #998).

**Comment by VSHY** [comment]
@komoku 
Also, it may be relates with https://github.com/OtterBrowser/otter-browser/issues/915#issuecomment-148908643.

**Comment by Emdek** [comment]
@pierreporte, these two are totally unrelated.

First one is result of last tab activity being set to current time after switching to it.
It's kind of like changing outcome by measuring it. ;-)
I'll welcome some simple solution that would allow to overcome that limitation in sane way.

The latter is upstream bug in ``QStyle`` that causes ``QTabBar`` to draw incorrectly dragged tab when it is added on top of ``QToolBar`` and had own ticket in the past already.

**Comment by komoku** [comment]
The simple solution that comes to my mind would be having a list of tabs ordered by "last time used" (probably there is already such a list) but *not* changing the "last time used" variable of a tab (and the order) when it is activated by an ActivatePreviouslyUsedTab action, but only when it is activated by other means (new tab action, clicking on the tab in the tab bar, etc.)

Or is there any pitfall that would make this not work?

**Comment by zakius** [comment]
I'd actually avoid the dreaded MRU behavior (introduced in windows' alt+tab as well for some reason) and use the display order order, or at least make it configurable
As well as I'd like to be able to not display tabs list when I press alt+tab, just directly switch to next tab without overlays

**Comment by ersi-dnd** [comment]
This Ctrl+Tab misbehaviour is rather obstructive. A workaround for the time being would be to duplicate the tabs list (the list that appears with Ctrl+Tab) in Menubar. Is it possible? Then I could select the tab from the list. 

And all menus should be of course navigable with arrows up and down.

**Comment by xploSEoF** [comment]
MRU is currently set up correctly - if you switch to the tab, it is now active. This should be the case - as was the case in Opera, and in any tabbed application (other than browsers). For large quantities of tabs it works better than cycling through, and matches the convention set by alt-tab. If you need to navigate to the third most recently used, don't release "ctrl" - i.e. "ctrl+tab+tab" will get you through.

Worth noting, MRU was introduced long before windows' alt+tab and has been a feature as long as cycling through items in a specific order - it's more intuitive and offers a quicker way to navigate through more things. I remember it on Windows 98, and an older Macintosh system.

That said, there should be provision for this being config driven - Opera 12.x has that option. I've therefore no doubt this will be config driven.

**Comment by zakius** [comment]
I don't want to go too deep in MRU vs List Order discussion, but after so many years since XP release I still get distracted by alt+tab MRU behavior, I get completely lost and my workflow is so broken I have to use mouse to select desired window. The list order seems more intuitive: you don't have to remember the order, you can just take a glimpse of buttons (or tabs) on bar and just press tab how many times you need to
If someone wants MRU it's fine, as long as list order is available

**Comment by ersi-dnd** [comment]
Agreed with zakius. By default, Ctrl+Tab should work as it works in old Opera. More options are fine, but all options should be configurable. In Opera, I am used to press Ctrl+Tab to first get up the list of tabs and then, as a second step, switch where I want to, if I don't reconsider meanwhile. 

Switching back-and-forth works smooth enough in Opera too - if you press Ctrl+Tab once AND release it, the switch happens. As long as you don't release it, there will be no switch and the tabs list will stay up. If you choose to stay with the current tab, press Ctrl+Tab again.

Current behaviour with Otter's Ctrl+Tab (immediate switch) is disorienting for those who are used to Opera.

**Comment by zakius** [comment]
I'm on the immediate switch side, without even showing list (the list is visible on tab bar anyway) if possible, but as otter is meant to be THE browser WE take control of, I guess sooner or later we will be able to choose that too

**Comment by xploSEoF** [comment]
Sounds like everyone agrees there needs to be a way to select from the three options... just like Opera 12.x

**Comment by Frenzie** [comment]
I just checked and Otter already has both Ctrl+Tab and Ctrl+F6 (and Ctrl+Shift+F6). But yeah, Opera also had an option to make Ctrl+Tab work the way that is immensely disorienting to me.

**Comment by k3dar** [comment]
workaround for set as Opera12 "Cycle without showing list" is change manually hotkeys in file: ~/.config/otter/keyboard:

[ActivateTabOnLeft]
shortcuts=1 Ctrl+Shift+F6 Ctrl+Shift+Tab

[ActivateTabOnRight]
shortcuts=2 Ctrl+F6 Ctrl+Tab

**Comment by zakius** [comment]
@up: thank you!
tip: on win7, don't know about others, you first have to copy default profile as it is not stored there (and I don't know yet where it is), then you can edit that copy manually

**Comment by PStokman** [comment]
ersi-dnd explains exactly what I'm having an issue with. When I want to switch to another tab that is not the previous tab using ctrl+tab, e.g. the tab before the most recent one, Otter switches to the recently used tab first before showing the list that allows to you see and properly select the tab you want using the tab key while holding ctrl. With the current behaviour, the order gets broken.

Example: I have 3 tabs open and switch between tabs 1 and 2 quickly. Now I want to do the same with 1 and 3. While I'm on tab 1, I press ctrl+tab, hold the ctrl key so it shows the tab list to be able to select tab 3. Now when I release the ctrl key, I switch to tab 3, but I went to tab 2 due to the fast switching being triggered first. So instead of my desired 1-3 switching, I'm now stuck with 2-3 switching. In order for me to get the desired result, I have to be on tab 2, so it switches to tab 1 first (because of the quick switching getting triggered instantly) and then go to tab 3.

This behaviour is not what Opera 12 does. It allows for fast tab switching, if you're just a bit slow it briefly pops up the tab list, but still provides a proper way to navigate to another tab by consecutively pressing the tab key while holding ctrl.

**Comment by ersi-dnd** [comment]
The way I used old Opera, I pressed Ctrl+Tab precisely to get up the tabs list. And if the highlight was not on the tab I wanted, then press Ctrl-Tab more.

So, if the tabs list is not coming up instantly, I find the entire Ctrl+Tab useless. (Yes, I know it works differently in other browsers, but that's why they are _other_ browsers.)

**Comment by zakius** [comment]
and that's why otter browser as THE browser should have options to choose MRU vs tab order and popup vs no popup, right?

**Comment by Emdek** [comment]
I think that we can consider this being done, I'll expose some of related options in Preferences too.
