### ISSUE TITLE
Old Opera and Safari extensions support

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#1022]
Because ,as I know, Old Opera extensions and Safari extensions do not need an api calls to work -
would sugest to implement their's support first! (and only after FF and Chrome extensions where needed specific api)

**Comment by Frenzie** [comment]
I'm not really sure what you mean by not needing API calls? Opera/Presto has what I consider [a superior API](http://www.opera.com/docs/userjs/specs/), but an API it is.

**Comment by DI555** [comment]
I mean that those ones don't need specific api-calls (in js body etc.) to work - its just [b]nude js[/b]+conf.page+button

**Comment by lollox** [comment]
If I can say my opinion, the market is moving towards the WebExtension API as an unique standard across all browsers out there. Old Opera APIs are no more, Firefox is going to drop support for "complete" extensions since they will drop XUL entirely. I don't like this very much, but this is the reality.

So, should a project like Otter really spent time and energies developing (and supporting) dead technologies? No one will develop old Opera extensions or XUL based extensions in a very short time, and old ones will be abandoned. 

In the end, I think Otter should only support WebExtensions API and give to it the best effort it can :)

**Comment by Frenzie** [comment]
I agree that supporting dead technologies would  hardly be the best use of
time.

**Comment by DI555** [comment]
Old Opera extensions is developing even now by the people who still love Old Opera !!!!!


noone said that Chropera team initiative with WebExtensions API will be supported by Chrome and MoFo... imo Chrome team will more develope it's api    and MoFo will stay with their's JetPack with translator from Chrome's api like they said))))


and (it's offtopic but never the less...) what people will do after FF drops XUL... imo drop FF itself )))
most users hates already now what they did with UI...

and imo XUL won't be supported by the Otter, because it's very hard staff.....but if sometime it somehow came true - it will be the masterpiece in the browser world.

**Comment by lollox** [comment]
@DI555 : maybe you're not well informed ;) ... Mozilla will drop XUL and all related techs in a few years. It's not something to decide. It's already established. They will switch to WebExtensions API as their unique extension platform (Jetpack will be supported 'till it will be possible but not forever)

I didn't understand what you mean about "Chropera team initiative" instead... WebExtensions is a common platform, not an Opera initiative. Chromium developed it and obviously support it, so I can't understand what you mean.

About the OT: yes it's very sad, but it's what the world is doing nowadays.

**Comment by Emdek** [comment]
@DI555, it's not planned, but if someone would create backend for them or some compatibility layer on top of APIs to be done as part of #42, then we could consider to merge it to "core" or keep it is as addon.
Related ticket: #336.
