### ISSUE TITLE
Middle click stopped working

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1189]
I updated to version 8114548c1325fe59d80512d3ae4fb7290555ce0b but I can’t say if the issue is more recent than the update, and I am sure it worked before since I use middle click a lot.

Now, the actions usually triggered by a middle click (on a link, open it to new tab; on a tab, close the tab) are not working at all.

Otter seems to detect middle click though, because the UNIX copy paste (middle click after a text selection) works.

**Comment by midluk** [comment]
I noticed that since 1ddfdd09e85cb3a7448ed6190e2c9c7f04fefa57 mouse gestures are not working any more. This seems to be the same problem.
Previous versions (until c482c64ab2382a40025f1ac42b75c8b200686ce2, but this version has some other problems, which are fixed in 1ddfdd09e85cb3a7448ed6190e2c9c7f04fefa57) had a "(default)" entry in the mouse section of the Advanced tab in the preferences. This is now gone. The list is completely empty.

Since the commits before 1ddfdd09e85cb3a7448ed6190e2c9c7f04fefa57 have some other weird problems, df65370a9f81743d6f11db89df7060761d785ab6 is the last working version for me.
