### ISSUE TITLE
Otter hangs when applying content blocking and then resumes

### ISSUE THREAD

**Issue by lynqa** [OtterBrowser/otter-browser#1207]
When content blocking is activated (no matter which filters), each time a webpage with ads is loading, the browser hangs and doesn't respond. However, after few seconds (but sometimes even half a minute), when the filters are already applied to the page, everything resumes to work. This doesn't happen when content blocking is off and I can see some ads before the lag – they disappear when the lag goes away. I'm using Otter on a very old netbook with 1GB RAM and Intel Atom processor, so maybe that's why it is so prominent.

I'm running Otter 0.9.11 beta 11 on GNU/Linux.

**Comment by bajasoft** [comment]
It is seems to be related to your older hardware according to you description. First versions of Atom had very poor performance - like 3x slower then Celeron with the same clock. Do you have any issues with different browsers like Firefox or Chrome?
For example on my 3,3GHz i5 it takes around 80 milliseconds and 35 MB of memory to load EasyList, which is one of the biggest list around (57 thousands of rules) and around 4 milliseconds for average regional list.

**Comment by wincak** [comment]
I have similar issues on somewhat better hardware (Core2Duo 2.2GHz, 4GB RAM). Actually this is the main reason why I (temporarily, I hope) switched to Firefox...
However, in my opinion hardware performance is not the problem here, the real question is why do the ads load at all?
With this implementation of ad blocking, you use bandwidth to load ads, then you take time to render them and when everything is done, you hide them.
Would it be possible to totally block any data transfer from hosts in blocklists, firewall fashion?

**Comment by bajasoft** [comment]
It is weird, I don't see any issue with loading of profiles on similar hardware (5 years old Athlon X2 2,6GHz, 4GB RAM). Is it happening every browser start or only after update? Do you see any error message in console?

If the request is recognized in active profile, it is blocked immediately and it is never downloaded and rendered. So it works exactly as firewall. You can check these requests in error console logged as information. We are hiding only elements defined directly in profile. Mostly white space left after blocked images, iframes etc. You'll be able to disable this hiding in future, it will be configurable.

**Comment by lynqa** [comment]
On the same netbook, Iceweasel 49 with uBlock Origin works well – it does never show the ads in the first place, but already displays the page without them. And it doesn't hang.
Also Otter doesn't output anything to terminal when the hang occurs.

**Comment by lynqa** [comment]
On the same netbook, Iceweasel 49 with uBlock Origin works well – it does never show the ads in the first place, but already displays the page without them. And it doesn't hang.
Also Otter doesn't output anything to terminal when the lag occurs.

**Comment by lynqa** [comment]
On the same netbook, Iceweasel 49 with uBlock Origin works well.

Also Otter doesn't output anything to terminal when the lag occurs; it occurs everytime, not only after updating.

**Comment by lynqa** [comment]
On the same netbook, Iceweasel 49 with uBlock Origin works well.

Also Otter doesn't output anything to terminal when the lag occurs; it happens everytime, not only after updating.

**Comment by bajasoft** [comment]
@lynqa, @wincak: What profiles do you have activated? I'll try to replicate this problem.

**Comment by wincak** [comment]
@bajasoft: Have there been some changes since v 9.10 concerning content blocking? I have updated to latest Otter version from AUR (0.9.11 beta 11) and I have difficulties to find a proper example of this issue..
However, with clean installation of Otter and profiles EasyList, EasyList Czech and Slovak it's possible to replicate it to some extent on website zive.cz. With these blocklists activated, it is possible to see "Blocked request" logs in console immediately after page loading starts. However, the panel on the top of the screen remains visible until all the other elements load and it gets hidden just after that. At the same moment an error log appears: "ReferenceError: Can't find variable: StartTipRotator". The browser lag occurs at the moment the panel hides.

**Comment by lynqa** [comment]
@wincak: I don't know… in my case there's no terminal output related to the issue. I made a quick video where I reproduced the problem, but this time the browser didn't return to work after it happened. https://www.youtube.com/watch?v=bvUrRIBgtK0

**Comment by bajasoft** [comment]
The issue is caused by cosmetic filters, they are just too slow on older hardware together with some heavy pages. There is greyed out check-box in Content Blocking preferences, which should allow to disable them. I'll try to implement it in near future.

**Comment by wincak** [comment]
@lynqa I meant the error log console (Menu->Toolbars->Show Error Console), not stdout/stderr.
@bajasoft Perfect. It's great to see how active development of Otter is.
