### ISSUE TITLE
the icons for button are too ugly

### ISSUE THREAD

**Issue by ellicefix** [OtterBrowser/otter-browser#1235]
Although its interface is very much like opera browser, but the icon is too ugly！

**Comment by pierreporte** [comment]
I do believe that, if someone were to found or make a good theme fitting the browser, it could replace the current one which is based on Crystal.

**Comment by c-cesar** [comment]
The best option is to use icons from system theme.

**Comment by mariokamenjak** [comment]
ellicefix, any suggestions?

**Comment by pierreporte** [comment]
I could suggest that we use [Icon8](https://icons8.com/), which is very large (thousands of icons in several colours) and has [very nice icons for desktop applications](https://icons8.com/web-app/category/all/User-Interface). This theme (or, more precisely, theme set) [is basically free](https://icons8.com/license/), yet it is limited to PNG format up to 100 px. “Popular” open-source projects can have the full set (with SVG and all) for free (whether Otter Browser fits in their criteria is up to them).

There are 7 proposed themes: *iOS 10*, *Windows 10*, *Windows 8*, *Material*, *Android 4*, *Color*, and *Office*.

------

Anyway, in my opinion an icon theme should be simple enough. Nnot necessarily minimal, but monochrome for sure. There are plenty of icon theme available, even though the best and the most complete for us are not completely free.

**Comment by mariokamenjak** [comment]
OK, but would the GPL be fine with it? I think it would be but I am asking just in case.

**Comment by pierreporte** [comment]
I don’t think license of Otter Browser has anything to do with the license of the icon theme. In fact, it is released under the [Creative Commons BY ND 3.0 license](https://creativecommons.org/licenses/by-nd/3.0/) which clearly states that you can do whatever you want as long as you credit Icon8 in the browser itself and you don’t make any modification.

About the modification, Icon8 has a [Github organisation)(https://github.com/icons8) that provides SVG source files with a different license. Their licensing policy sounds rather complicated, but I am confident with the fact that using the PNG icons is perfectly safe. Plus, because we can go up to 100px icons, we can have a high DPI version, so no problem.

**Comment by c-cesar** [comment]
"We distribute them under the license called Creative Commons Attribution-NoDerivs 3.0 Unported. Alternatively, you could buy a license that doesn't require any linking."
[Source](https://icons8.com/license/)
The "NoDerive" is not compatible with GPL, that explicitly allows modifications.

As I said earlier, the best solutions is to use the system theme. 
[Documentation about this](http://doc.qt.io/qt-5/qicon.html#fromTheme)
As said in docs, "By default, only X11 will support themed icons. In order to use themed icons on Mac and Windows, you will have to bundle a compliant theme in one of your themeSearchPaths() and set the appropriate themeName()"
So, a "default" theme must be elected and the used icons shipped for windows and mac.

**Comment by pierreporte** [comment]
@c-cesar It is already possible to use system icons in Otter, as @Emdek specified in https://github.com/OtterBrowser/otter-browser/issues/1203#issuecomment-251047815.

As for the license compatibiliy, is this really a thing for icon themes the way they are used in Otter?

In the end, Icon8 theme was just a proposition, as I said, there is plenty of similar themes available that could have a better and clearer licensing policy.

**Comment by c-cesar** [comment]
The Qt's bug in #1203 is fixed in 5.7, that I'm using, so in some time the default behavior can change back. Tomorrow I will try to test this bug in 5.7.

**Comment by Emdek** [comment]
Superseded by #1239.

BTW, current icon theme is based on Oxygen, not Crystal. ;-)

**Comment by Flashwalker** [comment]
in 2021 it's still black icons with a dark theme...
