### ISSUE TITLE
Allow to bypass right-click blocking

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1251]
Some websites disable right-click to “protect” their content from copying. Some other provide their own context-menu and need do disable the standard one. This situation made Firefox to have a very special way of bypassing the forbidden right-click: the user just has to press <kbd>Shift</kbd> and right-click at the same time.

It’s a must-have for Otter, as it gives full power to the user while keeping legit apps working.

**Comment by mariokamenjak** [comment]
I want this too.

**Comment by Emdek** [comment]
We can allow that, simply not delivering such event to webpage, but it would make sense only as temporary option since it would also break a lot of pages that use custom context menus etc.

I have no idea how to name it since while de facto it is only JS option but in reality it simply won't deliver right mouse button clicks to webpage.
AFAIR it shouldn't break anything else, just right mouse button handlers on webpages, at least right now.

**Comment by pierreporte** [comment]
It could be named “use native context menu” since the aim of the feature is actually to show the browser context menu.

**Comment by Emdek** [comment]
@pierreporte, I meant internal name of option (see **about:config**), UI part is the easier one. ;-)

**Comment by pierreporte** [comment]
@Emdek, why are you mentioning about:config? As you said in [your previous comment](https://github.com/OtterBrowser/otter-browser/issues/1251#issuecomment-276278765), this feature must be temporary. Do you want users to permanently prevent web pages to detect right clicks? If so, “AlwaysUseNativeContextMenu” seems good to me.

**Comment by Emdek** [comment]
@pierreporte, all options have to be declared in `SettingsManager`, so it needs proper name (identifier) there to be used in our configuration system.

**Comment by pierreporte** [comment]
OK, I haven’t realised. Then, what about `ForceNativeContextMenu`?

**Comment by Emdek** [comment]
@pierreporte, there is one more and even more important blocker, *Browser* category is already overflowing with variety of unrelated options, so I think that it's time to move out JS related stuff to won category, there are three options:
1. only move JavaScript prefixed entries to own *JavaScript* category (using such name might be not future proof, even classic Opera avoided that by using *script* instead of *JavaScript* in similar option names);
2. also move there stuff that is trigerred by JS like geolocation and fullscreen requests;
3. move both into *Permissions* category together with option to load images and plugins (since they are all in fact permissions).

I have to do this first and in single migration to avoid extra noise.

**Comment by Emdek** [comment]
Uhm, apparently we have such option already, but it might need renaming and changing implementation a bit.

**Comment by Emdek** [comment]
It seems that it doesn't work with QtWebEngine anyway.
