### ISSUE TITLE
Keep support of sessions .ini files

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#1292]
Please, keep support of sessions .ini files! It hardly needed for using with good-old Opera Presto in two ways!!!
Yes .json is good with FF using, but old .ini format needed so much!!!
Please make an about:config switch that could be possible keeping(and saving to) two files together - .json and .ini! It won't take much space on a disk !!!

So we may have and so-called the second, backup copy of a using session also!!!
(Do you remember that Opera Presto was creating the .bak files as a backup copy - so could be using the .ini files like a backup copy of session!!!)

**Comment by Emdek** [comment]
@DI555, they were **never** interchangeable with classic Opera in the first place.
We can't support both (that will simply break stuff) and we can't keep using old INI format since it prevents adding new features in sane way and in fact it is way worse for manual editing (since it depends on strict numbering of entries and breaks easily).
I believe that root cause of that ticket are issues with migrating old sessions (#1276).
