### ISSUE TITLE
Adress bar and Bing

### ISSUE THREAD

**Issue by finkiki** [OtterBrowser/otter-browser#1296]
Add Bing as defaut search engine cause a 301 error when i try to access a site from the bing search result page after using the adress bar. 

It's work fine if i use the top-right field and use the bing search.

Windows 7/weekly 165.

**Comment by VSHY** [comment]
_> Add Bing as defaut search engine cause_
I'm against. I always have to remove it.

**Comment by Emdek** [comment]
@finkiki, you mean that you are getting 301 error when using Bing while searching from address field but not when using search field?
Have you modified search engines list in some way (updating, adding or editing entries) other than changing defaults?
Are you using keywords or simply pressing Enter after entering term?
What term is that? If it matches URL or host name then it might end up interpreted that way (it will be loaded instead of searching), depending on what you do.

**Comment by finkiki** [comment]
In both case (adress field and search field), Otter show the bing result page. But if i use the adress field, i cannot access any site because i get 301 error.
I didn't modify anything in the search engine, just put Bing as defaut search in Parameters.
After some tests, it's look like pressing Enter or clicking or use keyword in the adress field didn't change anything.

For exemple, typing "empiresmod" using bing in the adress field will show the bing result page but clicking on any result brings a 301. On the contrary, using the search field using bing will show the bing result page and clicking on any result load the site. 

Note what, i didn't get this problem using yahoo or google for exemple.

**Comment by Emdek** [comment]
@finkiki, cannot reproduce on Windows 10.
Let me know if you will manage to get some more information.
