### ISSUE TITLE
html5 "pattern" attribute does not work

### ISSUE THREAD

**Issue by chief-kh** [OtterBrowser/otter-browser#1321]
browser doesn't check pattern on form submit for inputs
`<input type="text" name="numbers" pattern="^([0-4]?[0-9] ){6}[0-2]?[0-9]$" />`

work fine in firefox and chromium

**Comment by Frenzie** [comment]
That's a QtWebKit issue. I haven't checked. WebKit has partially supported this since '09 (see [here](https://bugs.webkit.org/show_bug.cgi?id=25552)), with the (peculiar) caveat that it still allows invalid submissions. Here's a testcase to demonstrate:

```html
<!DOCTYPE html>
<style>
input:invalid{background:red}
input:valid{background:green}
</style>
<form>
Five uppercase letters: <input type="text" name="country_code" pattern="[A-Z]{5}">
<input type="submit">
</form>
```

Unfortunately this issue still seems to be present in the AppImage-bundled, newer QtWebKit as well.
