### ISSUE TITLE
Print preview doesn't work

### ISSUE THREAD

**Issue by fturco** [OtterBrowser/otter-browser#1339]
It seems print preview doesn't work in Otter. At least it doesn't work for all websites I tested. Otter just displays an empty window with zero pages:

![print-preview](https://cloud.githubusercontent.com/assets/5459866/24877605/24df51a0-1e30-11e7-93f9-c59d5d633d84.png)

Otter 0.9.12 beta 12 on Gentoo Linux.

**Comment by Emdek** [comment]
@fturco, which backend, which pages?
Most likely not our bug, but something to be relayed to QtWebKit or QtWebEngine devs.

**Comment by fturco** [comment]
It happens with any website, for example http://otter-browser.org/. WebKit backend (legacy) 538.1.

**Comment by Emdek** [comment]
@fturco, cannot reproduce (using both legacy QtWebKit from 5.6 and revived with Qt 5.8), it appears to be some issue with Qt on your system.
Try our AppImage that uses Qt 5.6 and revived QtWebKit, it requires OpenSSL 1.0 and GStreamer 1.x.

System wide you should consider switching to revived QtWebKit:
https://github.com/annulen/webkit/wiki/Comparison-with-QtWebKit-5.6
AFAIK there should be some ebuild around too.
Just make sure that assertions won't get enabled since they used to generate a lot of useless backtraces under Gentoo.

**Comment by fturco** [comment]
There's `dev-qt/qtwebkit-5.8.0` in the qt overlay, but it's hard masked with the following warning:

```
# /var/portage/repos/qt/profiles/package.mask:
# Michael Palimaka <kensington@gentoo.org> (25 Jan 2017)
# Untested work in progress.
# Guaranteed to break your system horribly or your money back.
```

So I'm a little bit scared of breaking my system.

**Comment by Emdek** [comment]
@fturco, that one is also legacy, you can build revived locally and link against it when building browser, that would be safest way, although it shouldn't break anything anyway (see comparison table), since it kept API and ABI compatibility and only few packages use it.
You can also stick to weekly AppImage for now.

**Comment by fturco** [comment]
Wait! I discovered that `dev-qt/qtwebkit-5.7.1` was built without the `printsupport` USE flag. 

Description:

> Enable printing via dev-qt/qtprintsupport

I'm rebuilding qtwebkit now...

**Comment by Emdek** [comment]
@fturco, well, I guess that it resolves this one for sure. ;-)
Anyway, you should consider switching to revived, it's big leap forward, it brings like three years of upstream improvements and fixes from upstream WebKit back to QtWebKit.

**Comment by Emdek** [comment]
BTW, it that option is supported by Qt itself then it should show some sort of message in that case, current state is bogus and deserves report to bugreports.qt.io.

**Comment by fturco** [comment]
I confirm that print preview in Otter works fine now. I just had to enable the `printsupport` USE flag for package `dev-qt/qtwebkit-5.7.1` and restart Otter.
