### ISSUE TITLE
Otter freezes when loading spreadprivacy.com website

### ISSUE THREAD

**Issue by fturco** [OtterBrowser/otter-browser#1348]
Otter freezes every time I load the https://spreadprivacy.com/ website (DuckDuckGo official blog). Nothing happens, even after waiting for 5 minutes. Otter window remains stuck and doesn't respond to mouse clicks. Cleaning `~/.config/otter` and files in `~/.cache` doesn't help. I'm using Otter 0.9.12 beta 12 on Gentoo Linux. Web backend: WebKit Backend (legacy) 602.1.

**Comment by BorutAtGit** [comment]
This seems not to happen with Weekly 170 and WebKit legacy 538.1 under WinXP.

**Comment by beastie1** [comment]
It works fine here too. Latest (almost) from MASTER with Qt 5.6.2, WebKit 538.1 under FreeBSD.

I tried with my normal profile and with a new one, with and without JavaScript.

![spreadprivacy](https://cloud.githubusercontent.com/assets/6757832/25070200/c616ae6e-22a0-11e7-9f33-5bcf72046837.jpg)

**Comment by fturco** [comment]
I did some more testing today. It seems my problem with spreadprivacy.com happens only if JavaScript is enabled.

**Comment by Emdek** [comment]
@fturco, it might be some regression in QtWebKit, compare against this:
https://github.com/OtterBrowser/test-qtwebkit
It should behave the same way.
No freeze here, some post TP5 commit (one week old).

BTW, 602 sounds like revived QtWebKit, no idea why it gets note that it is "legacy", we check version number this way: older than 600 is legacy, otherwise it's revived.

**Comment by fturco** [comment]
I can load the website with test-qtwebkit without problems...

**Comment by Emdek** [comment]
@fturco, could you try some later release (for example weekly 160, newer ones have some regressions) or current master? 
I would suggest to run them with ``--portable`` argument, since they are not fully backwards compatible (can overwrite session file etc.).

**Comment by fturco** [comment]
I can reproduce the same problem with the latest git version (`=www-client/otter-9999`).

**Comment by cofi89** [comment]
I can reproduce too.  

Also, same happens on Manjaro forum. Loading of additional replies or topics during scrolling triggers it every time.
To reproduce, go to: https://forum.manjaro.org/t/secure-boot-with-manjaro/1839 and keep scrolling down quick with your mouse == eventualy it freezes ( usually around post 8 ).  

Reproducable in `qt-demo-browser` and `smtube` ( because why not :smile: ).  
In my case, both M. forum & Spreadprivacy are reproducable in `test-webkit` **if** inspector is closed.
Though it seems to "resist" the M. forum more, because it takes much more scrolling to trigger the freeze ( compared to Otter and the above^ ). With spreadprivacy it's almost instant == page shows and then freezes. 

Leaving the inspector open == no freeze.

----------

Latest Otter from master, QT 5,7,1, Deb Stretch, WK TP5.

**Comment by fturco** [comment]
I can confirm what @cofi89 said:
* Otter freezes on Manjaro forum after scrolling to the bottom of the page
* test-qtwebkit freezes on spreadprivacy.com immediately when inspector is closed
* test-qtwebkit freezes on Manjaro forum after scrolling to the bottom of the page

**Comment by Emdek** [comment]
Thanks for testing, inspector related issues look like:
https://github.com/annulen/webkit/issues/90
If these issues are reproducible in *test-qtwebkit* then it looks like it needs to be solved on QtWebKit level, I'll pass these findings to @annulen.

**Comment by annulen** [comment]
Note that to be annulen/webkit#90 issue should a) be reproducible only with revived QtWebKit, and b) freeze should be accompanied with high CPU usage. Otherwise it's a different issue.

**Comment by bcoolumbo1** [comment]
Otter completely freezes when navigating back or closing a sub-page from RTL news website.
Gdb shows me no error. Even when closing the gdb terminal, the frozen otter window stays open.
linux, otter devel, webkit
