### ISSUE TITLE
Uploading files to github doesn't work

### ISSUE THREAD

**Issue by nortexoid** [OtterBrowser/otter-browser#1384]
Trying to upload a file to a github repo doesn't work. A file dialog pops up and then nothing happens.

**Comment by m4sk1n** [comment]
@nortexoid, can you provide more info? What OS and what version of Otter?

**Comment by nortexoid** [comment]
Sorry, I head meant to add that. I'm running linux, Ubuntu 16.04-based KDE Neon User Edition, otter browser 0.9.91 (weekly 183). I'm using the weekly ppa.

**Comment by nortexoid** [comment]
Perhaps I should also mention the qt version is 5.9.1 and plasma version 5.10.3.

**Comment by Emdek** [comment]
@nortexoid, that sounds like legacy QtWebKit, and github is known to not care about anything older than three years...
Try our AppImage instead, it uses revived QtWebKit.

**Comment by nortexoid** [comment]
I tried running the AppImage but get this:
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
./otter-browser: relocation error: /lib/x86_64-linux-gnu/libssl.so.1.0.0: symbol EVP_aes_128_cbc_hmac_sha256, version OPENSSL_1.0.2 not defined in file libcrypto.so.1.0.0 with link time reference

Outdated openssl? I'm surprised that qtwebkit would be outdated given that I'm running qt 5.9.1, and I have installed libqt5webkit5/xenial,now 5.9.1+dfsg-1+16.04+xenial+build14 amd64.

**Comment by Emdek** [comment]
@nortexoid, that means that you have incompatible OpenSSL version (they broke ABI compatibility in minor release), and that one is not easy to solve (unless Ubuntu provides OpenSSL 1.0.x too)...
That version of QtWebKit wasn't updated since 2013, except few fixes, here is comparison:
https://github.com/annulen/webkit/wiki/Comparison-with-QtWebKit-5.6

**Comment by beastie1** [comment]
It's most definitely related to legacy WebKit. I've been having the same problem for months now. I can't edit my comments either or preview a new one. When I need to do any of these, I use legacy Opera. Everything works perfectly then.

**Comment by beastie1** [comment]
@Emdek

> github is known to not care about anything older than three years...

Interestingly, Presto works like a charm. But then again, it's only 2 years old. ;)

**Comment by nortexoid** [comment]
I see. Still not sure how to get a build using qtwebengine instead, but at least I now know what the issue is (sort of)!

**Comment by beastie1** [comment]
The AppImage Emdek mentioned earlier is based on revived WebKit. There are links to the latest version on the [home page](http://otter-browser.org/).

The packages based on WebEngine can be found in the experimental directory on SourceForge, but they're for Windows only.

**Comment by nortexoid** [comment]
Thanks very much for the clarification!

**Comment by Emdek** [comment]
@beastie1, nope, classic Opera has various issues on github, since recently it is not even possible to manage project (for example managing labels for an issue is broken), nick completion in comments does not work anymore etc.
And for long time it often hides list of files when viewing subdirectory listing (code viewer) and requires reload to show it.
