### ISSUE TITLE
Open "about:cookies" bug

### ISSUE THREAD

**Issue by CyberC123** [OtterBrowser/otter-browser#1392]
Hey,
when I login to github.com and open the "about:cookies" page during the loading process otterbrowser crashed.
No succes with eraseing the history and cookies.
I have only the GitHub page open.

Version:
	Main Number         0.9.91
	Weekly Number       183
	Context              weekly 183
	Web Backend         WebKit-Backend 602.1

Environment:
	System Name                   Windows 7 SP 1 (6.1)
	Build ABI                     x86_64-little_endian-llp64
	Build CPU Architecture        x86_64
	Current CPU Architecture      x86_64
	Build Qt Version              5.9.1
	Current Qt Version            5.9.1
	Locale                        de_DE

**Comment by Emdek** [comment]
@CyberC123, cannot reproduce here, using both Windows 10 64 bit and Windows 7 32 bit.
Can you reliably reproduce it?

**Comment by BorutAtGit** [comment]
Also can not reproduce with a 32 bit build under Win 7 64 bit. I see nine github.com cookies and am able to see the details of each one of them. My cookies options: Accept always, Keep until current session is closed, Never accept 3rd party cookies. Running in a portable mode.

**Comment by CyberC123** [comment]
Okay I have found the problem in the "cookies.dat" file
Here is a zip with a working cookies file and my broken cookies.dat
[cookies.dat.zip](https://github.com/OtterBrowser/otter-browser/files/1184915/cookies.dat.zip)
There is a control character at the end of file. (Visible with Notepad++ for example)
I haven't edit this file.

**Comment by Afril** [comment]
It seems I found one way how to reproduce the bug:

1. Rename Otter's previous config directory so that Otter will start in an unconfigured environment.
2. Start Otter
3. Go to Preferences->Privacy
4. Select "Keep until: Current session is closed"
5. Select "Accept third-party cookies: Never"
6. Unselect "Enable cookies"
7. OK
8. On the start page press F12, then Accept Cookies -> Always
9. Go to the URL [http://www.weatherzone.com/](url)
10. Close Otter
11. Rerun Otter; the previous website should reopen.
12. Go to Tools->Cookies

Backtrace:
`#0  0x00007fffed11b0eb in QItemSelectionModel::selectedIndexes() const () at /usr/lib64/qt5/../libQt5Core.so.5
#1  0x0000000000abe110 in Otter::CookiesContentsWidget::updateActions() (this=0x141fe70)
    at /home/dieter/src/otter-browser-0.9.99.3/src/modules/windows/cookies/CookiesContentsWidget.cpp:402
#2  0x0000000000abcc76 in Otter::CookiesContentsWidget::handleCookieAdded(QNetworkCookie const&) (this=0x141fe70, cookie=...)
    at /home/dieter/src/otter-browser-0.9.99.3/src/modules/windows/cookies/CookiesContentsWidget.cpp:261
#3  0x0000000000abb80e in Otter::CookiesContentsWidget::populateCookies() (this=0x141fe70)
    at /home/dieter/src/otter-browser-0.9.99.3/src/modules/windows/cookies/CookiesContentsWidget.cpp:85
#4  0x0000000000ac21d8 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Otter::CookiesContentsWidget::*)()>::call(void (Otter::CookiesContentsWidget::*)(), Otter::CookiesContentsWidget*, void**) (f=(void (Otter::CookiesContentsWidget::*)(Otter::CookiesContentsWidget * const)) 0xabb77e <Otter::CookiesContentsWidget::populateCookies()>, o=0x141fe70, arg=0x7fffffffcf48)
    at /usr/lib64/qt5/include/QtCore/qobjectdefs_impl.h:136
#5  0x0000000000ac1f06 in QtPrivate::FunctionPointer<void (Otter::CookiesContentsWidget::*)()>::call<QtPrivate::List<>, void>(void (Otter::CookiesContentsWidget::*)(), Otter::CookiesContentsWidget*, void**) (f=(void (Otter::CookiesContentsWidget::*)(Otter::CookiesContentsWidget * const)) 0xabb77e <Otter::CookiesContentsWidget::populateCookies()>, o=0x141fe70, arg=0x7fffffffcf48) at /usr/lib64/qt5/include/QtCore/qobjectdefs_impl.h:169
#6  0x0000000000ac1ce3 in QtPrivate::QSlotObject<void (Otter::CookiesContentsWidget::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x19d7b20, r=0x141fe70, a=0x7fffffffcf48, ret=0x0) at /usr/lib64/qt5/include/QtCore/qobject_impl.h:120
#7  0x00007fffed199a99 in QSingleShotTimer::timerEvent(QTimerEvent*) () at /usr/lib64/qt5/../libQt5Core.so.5
#8  0x00007fffed18e8eb in QObject::event(QEvent*) () at /usr/lib64/qt5/../libQt5Core.so.5
#9  0x00007ffff77ed51c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib64/qt5/../libQt5Widgets.so.5
#10 0x00007ffff77f49c7 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/qt5/../libQt5Widgets.so.5`

Otter Browser diagnostic report created on 2018-09-12T12:01:51Z

Version:
	Main Number         0.9.99
	Weekly Number        RC 12
	Context              weekly  RC 12
	Web Backend         WebKit Backend 602.1

Environment:
	System Name                   Mageia 6
	Build ABI                     x86_64-little_endian-lp64
	Build CPU Architecture        x86_64
	Current CPU Architecture      x86_64
	Build Qt Version              5.9.4
	Current Qt Version            5.9.4
	Locale                        sv_SE

**Comment by Emdek** [comment]
@Afril, while I was able to reproduce it only once (and it was non debug build...) the above change should fix it.

**Comment by Afril** [comment]
Fine, Otter does no longer crash on the above described procedure.
