### ISSUE TITLE
F6 for ActivateAddressField instead of F8 ?

### ISSUE THREAD

**Issue by eMPee584** [OtterBrowser/otter-browser#1398]
In every other browser seems to be on F6. Was there a specific reason to put it on F8?

**Comment by Frenzie** [comment]
I have at least 6 browsers on my computer that use <kbd>F8</kbd> by default. In alphabetical order by executable name:

1. opera (real Opera)
2. opera-beta
3. opera-developer
4. otter
5. vivaldi
6. vivaldi-snapshot

I think that should answer whether there's a specific reason. ;-)

**Comment by eMPee584** [comment]
Ah ok, so it's an opera thing. 😃 
Chrome/IE/Firefox use F6.

**Comment by Emdek** [comment]
We can have both, unless it would conflict with some action from classic Opera, but I don't see it being used there.

**Comment by Frenzie** [comment]
IE very much uses <kbd>F4</kbd>, although Edge seems to have decided to join the Chrome would-bes by switching to inferior <kbd>F6</kbd>. I'm not really kidding. Although you might argue the keys are arbitrary, <kbd>F4</kbd>, <kbd>F5</kbd>, and <kbd>F8</kbd> are the easiest keys to use for frequent functions like selecting the addressbar and refreshing. That's why Microsoft used <kbd>F4</kbd> and <kbd>F5</kbd> across its applications, insofar as applicable. Opera happened to settle on <kbd>F8</kbd> instead. Firefox' <kbd>F6</kbd> and Chrome's later copying of it are imo mystifying, but I assume it might go back Netscape. Edge's switch to Chrome's inferior shortcut is all the more inexplicable since they already had a well established usage pattern.

/rant

But since it won't conflict with anything I guess it won't hurt. :-P

Btw, in Vivaldi <kbd>F6</kbd> opens the bookmarks panel.

**Comment by beastie1** [comment]
I agree with Frenzie 100%. The 104-key PC keyboard, the most common one nowadays, has 12 function keys usually divided into 3 groups of 4. Important functions should be tied to the "edge" function keys for higher ergonomic access. So I'm perfectly content with <kbd>F4</kbd>, <kbd>F5</kbd>, <kbd>F8</kbd> and <kbd>F12</kbd> being exactly as they were/are in classic Opera and Otter.

**Comment by eMPee584** [comment]
ok maybe my stats were wrong, I can only remember to ever have used F6 to switch to the address bar, in several browsers (konqueror and the mainstream ones). But as I can easily configure F6 instead of F8, I'm fine with that. To change the default, real figures should be gathered for which percentage of browsers do use what key to trigger this action. And all the others.. Or not. : )

**Comment by Frenzie** [comment]
In something like Konqueror I can't help but wonder if it was a misguided attempt to be different than Windows Explorer. Oh well, I think just about every application that has a refresh function uses <kbd>F5</kbd> for it. :-P

**Comment by Emdek** [comment]
@eMPee584, it's not a problem to have it as secondary (unless we would like to mimic Vivaldi), some actions have even four shortcuts in total. ;-)

BTW, we could also bundle profiles that use just the shortcuts used by Firefox etc., so users could switch between whole sets easily.
But someone would have to prepare such list first...
