### ISSUE TITLE
Multiline text forms have no Add note or Add from note action

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1437]
In old Opera, when the focus was in a multiline text form, such as in a forum, then in the right-click menu there was the item "Add note", followed by the list of all notes, so as to select it and instantly complete the text for the form.

**Comment by Emdek** [comment]
@ersi-dnd, we have both and in the same order as in classic Opera.
Perhaps you are using custom menu definition (*webWidget.json*).

**Comment by ersi-dnd** [comment]
You are right, topmost by default. Sorry, I should always check with a clean profile. Usually I do that, but I should always do that.

**Comment by ersi-dnd** [comment]
I tried to remove the relevant section in /otter/menu/webWidget.json. I hoped this would give me the current default menu. But this left me completely without any menu in forms (while other menus remained working). So I removed webWidget.json altogether. This seems to give me the default menus. 

Is the relevant section that which begins
```
            "type": "include",
            "includeIn": "edit",
```
?

**Comment by ersi-dnd** [comment]
I seriously wonder why this behaviour, as follows,

A. I delete a section from webWidget.json and I do not have that particular menu at all anymore.
B. I delete the entire webWidget.json and I get the default menus.

Where are the default menus? Can I edit menus?

**Comment by ersi-dnd** [comment]
Okay, I guess this is the one https://raw.githubusercontent.com/OtterBrowser/otter-browser/master/resources/menu/webWidget.json

- So I save it as /menu/webWidget.json and then I can edit menus? 
- Is it indeed so that all sections must be there, not only the ones I want to change?
- And when you change the json again, then my edited file becomes problematic again?
- And I keep wondering, how does it work that when I delete my edited json altogether, all menus begin to work again? Why can't I use a short custom menu file just for two-three menus that I want to change?

**Comment by Emdek** [comment]
@ersi-dnd, these have to be edited carefully, this one is the most complex of them all, due to these include and exclude rules.
First of all, make sure that JSON is valid before trying result, for example using this tool:
https://jsonlint.com/

**Comment by ersi-dnd** [comment]
@Emdek 
> these have to be edited carefully, this one is the most complex of them all, due to these include and exclude rules.

This is why JSON language is not good, with all those various parentheses and punctuation and silly beautification to be meticulously observed. JSON may be more "powerful", but INI is straightforward and instantly editable without a steep learning curve and no need to pay attention to parentheses and punctuation. Anyway, of course I am careful either way and trying my best to live with it.

So I take it that the answers to my questions are:
- Yes, we need the complete webWidget.json in the profile. Any missing section means a corresponding missing menu. There is no graceful fallback to a system/main file anywhere else, except when the entire file is missing in the profile.
- Yes, as Otter's action list evolves/changes, the custom file in the profile becomes incompatible.

**Comment by Emdek** [comment]
@ersi-dnd, well, it's not perfect but now it's not the time to change it, and one thing for sure, INI is not a solution for nested data structures. :-P

About incompatibility, it depends:
 -  keyboard shortcuts, mouse gestures, toolbars, sessions, options etc. are guaranteed to be compatible or be migrated when needed for several months now (of course sometimes it might break due to some bugs... or restoring older backups after migration), with few exceptions for stuff that was introduced in between main releases (living on the edge has some consequences ;-));
- menus are not covered yet, they are not finalized yet (the minimum is to finish concept that allows to merge action lists without use of submenu - example: see how spell checking suggestions are implemented in many browsers, they are added at the top of menu, another uses case is our Bookmarks menu, right now two first actions are hardcoded, and I want it to be flexible too), but they might be around 1.1 maybe, for sure we should try harder when there will be finally an official editor.

We need to introduce header with version for more files (like in keyboard and mouse profiles), these that can be cloned or edited, so we can warn about definitions from version older than current one, warn that custom definition might be missing some stuff (migrations cannot add such stuff like new menu section etc., it's too complex and we would risk damaging custom definitions).
I have a draft for such idea for some time already, it would be a good idea to implement it in time for 1.0.

Surely we will need special section about compatibility and migrations in our docs.
