### ISSUE TITLE
Tabs icons when browser starts

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#145]
If you use delay loading of tabs, when browser starts all indicators must display sites favicons instead of page load indicator. Otherwise, when a large number of tabs not find the required.

**Comment by PStokman** [comment]
Old discussion, but what about making favicons partly transparent when the tab has not finished loading? I was thinking about using greyscale, but that does not work when the favicon doesn't have any colour, like the Github favicon.

**Comment by pierreporte** [comment]
@PStokman A better solution would be to add something on one of the top corners, like Opera and Vivaldi, for example a little “page-fold” or a coloured dot.

**Comment by PStokman** [comment]
@pierreporte yes, but until that can be done (if it's not possible atm), it is a viable alternative. I believe that once skin support is in place, it should be up to the skin to determine how to deal with this.

After all, in Opera it is done the same way. The default skin uses a fold, while others use text colours or a big dot.

**Comment by Emdek** [comment]
@pierreporte, that approach is not possible without proper styles support since so far I haven't found any platform that would have own native implementation of that concept, and drawing such stuff on top of existing styles will end badly.
It seems that after all defaulting to changing slightly text color might be best option for now.
Note that I would only change behavior for unloaded tabs, not for tabs that are actually loading at the moment.

**Comment by Emdek** [comment]
One "minor" detail, before #820 will be done we won't see many icons right after start anyway...
And storing them in session would probably be one step too far. ;-)
