### ISSUE TITLE
Otter browser native video playback.

### ISSUE THREAD

**Issue by fcore117** [OtterBrowser/otter-browser#1464]
Please add native video support with FFmpeg like Chromium instead of operating system based trash codecs, i cannot play videos at all as i do not have Microsoft media codec bloatware installed, Windows N version.

**Comment by Emdek** [comment]
@fcore117, that's opposite of native support. :-P
If you want non native multimedia backend then you can use "-xp" package, it's using GStreamer instead of Media Foundation (GStreamer can use ffmpeg / libavcodec too) since it's not available under Windows XP.
Another option is to use experimental QtWebEngine (Blink) backend which forces non native codecs, you can find it in "experimental" folder.

**Comment by fcore117** [comment]
I hope in far future when Otter is ready then maybe you can consider releasing Otter with integrated codecs version too. Currently i use Chromium(not Chrome) with all codecs enabled but i would gladly ditch it when Otter will be ready :)

**Comment by Emdek** [comment]
@fcore117, it won't get any better than "-xp" package combined with ffmpeg / libavcodec, there exists private build that has all needed codecs including H264 but thanks to software patents it cannot be distributed, at least not until someone will prepare recipe to build GStreamer and its codecs against OpenH264.

**Comment by fcore117** [comment]
Please publish a way to build it like that "private build" i could publish those builds in future myself as i dont give damn about patents.

**Comment by mariokamenjak** [comment]
But you could get him in legal trouble and the entire otter project.

**Comment by fcore117** [comment]
for example i build ffmpeg-fdk-aac and i live in EU

**Comment by beastie1** [comment]
You can do whatever you want on your machine because no one cares enough to check what you're doing there. But doing so publicly is like opening a legal Pandora's box.

Copyright law is such a complex subject that a lawyer's service is required to sort everything out properly.

Some rules apply to the EU, some don't. Besides you're talking about the Internet: everything is accessible to everyone everywhere and the server (and its mirrors?) on which you store your builds may not be in the EU.

Saying you don't give a damn is easy, but with such a mindset don't be surprised if your account gets suspended out of the blue. ;)

**Comment by fcore117** [comment]
If i distribute something then i distribute outside Github as i know Github is US based. My current Chromium is btw supporting all needed codecs without Windows media trashware and it is actually built in EU, i do not tell address here.

**Comment by mariokamenjak** [comment]
How about, don't distribute it at all and just make it for yourself?

Copyright law is pretty much international.

**Comment by fcore117** [comment]
Ok i would gladly do it for "myself" if way will be published in future when otter will be ready. 

It would be logical to include codecs as browser like Otter is free non-profit software, patents should earn money from stuff that is commercial and sold. There is times when logic must win.

**Comment by Emdek** [comment]
@fcore117, it's all there, you just need to build compatible GStreamer plugins, using ffmpeg or libavcodec (mentioned build was using this one, since only this one was already prepared to use with MXE) and place them in correct directory (*lib/gstreamer-1.0/*).
