### ISSUE TITLE
Discussion: Engine future?

### ISSUE THREAD

**Issue by mariokamenjak** [OtterBrowser/otter-browser#1465]
Will we forever be on revived QTWebkit?
Will Blink ever be a default and what needs to change in upstream for that to happen?
Servo maybe?
Anything else(KHTML?)?

What are the pros and cons of each?

**Comment by orto-dox** [comment]
I think that we must first determine the criteria by which we select the engine.
My important criteria are:
1. Less resource consuming. Now Otter-Browser eats RAM less than any other browser (except links or dillo ofcourse:)). If other engine will eats more resources, why we need to use them? Because there is so much browsers, and any of them works... But any of them consumes all available RAM in a hour. 
2. Vitality of selected engine. If for example QTWebkit will be dropped by developers, I think it is a good reason to view on other ones.
3. The man-hours needed for changing engine. Now there is about 2.5 contributors to Otter-Browser codebase, if work for changing engine will be hard, who will do it?

**Comment by mariokamenjak** [comment]
For me the primary concerns are website compatibility and the speed of website loading. Webkit is fine on the speed department but when it comes to compatibility with websites it is showing signs of aging.

**Comment by Emdek** [comment]
@mariokamenjak, currently only (revived) QtWebKit can satisfy our needs, QtWebEngine is simply not up to the task since it lacks many features and not all of them can be patched using JS.
The only interesting alternative right now would be Servo, but integrating it properly would require too much work, but if some third party entity would work on it (perhaps Jolla would be interested, since they were using Qt bindings for Gecko already) then we could add another backend.

@orto-dox, legacy QtWebKit is deprecated, but there is [revived QtWebKit](http://qtwebkit.blogspot.com/), it's around long enough so even Ubuntu finally picked it up for their next release.

**Comment by alekksander** [comment]
> Jolla
?

**Comment by awilfox** [comment]
The fact this browser uses QtWebKit instead of QtWebEngine is the main reason we at Adélie want to ship Otter as our primary browser.  We do not want to ship Chrome or Chromium-based software because of privacy concerns and the difficulty of building it on non-x86 computers.

Please do not leave us without a good, portable, privacy-conscious browser. :cry:  Keep going with QtWebKit.

**Comment by Sa-Ja-Di** [comment]
My vote of love is also revived QTWebkit. Chromium is garbage and Mozilla's new Frankenstein creation... as they serve the plain Jane/Joe today.. they would make it really  hard  for sure to implement some customization features, given their rather long time of dislike for both, power users and features as a whole since quite some years already.
