### ISSUE TITLE
cryptowat.ch doesn't work

### ISSUE THREAD

**Issue by testnameC04** [OtterBrowser/otter-browser#1480]
Such an online graph site as https://cryptowat.ch/gdax/ltcusd does not show the data on the last Otter Browser version to date.

It does not work on Firefox ESR 38.5.0.
It works fine on Firefox ESR 52.3.0. But my computer operates very bad with Firefox ESR 52.3.0, I have to close all other programs to give it enough RAM.

OS: Windows XP SP3.
RAM: 2 GB.

**Comment by Emdek** [comment]
@testnameC04, it seems to be one of these issues that require waiting for fix in QtWebKit.

**Comment by Emdek** [comment]
As noted by @annulen it turns out that some scripts get blocked by CSP rules.
The good news is that there exists workaround, by changing User Agent for that domain to:

> Mozilla/5.0 (%Platform%%Security%%Subplatform%) AppleWebKit/%WebKitVersion% (KHTML, like Gecko) %AppVersion Version/9.0 Safari/%WebKitVersion%

You can declare new User Agent in Preferences -> Advanced -> Network and then set it as default for this domain using Website Preferences -> Network.
