### ISSUE TITLE
Issue with cookie search

### ISSUE THREAD

**Issue by Sa-Ja-Di** [OtterBrowser/otter-browser#1502]
If i go into the Cookie sidebar menu point and want to delete for example Google related ones, i can not type Google - as there are shown no entries.

What works is if i type G - which then shows all G entries.

Works with every single letter, but if i use more than one - no entries are shown.

Windows only issue?

**Comment by Frenzie** [comment]
No, it's the same on Linux. The search is only in cookie content while the domain is ignored. I'm not sure if that's intentional but it seems counterintuitive.

## A few ads.whatever domains
![screenshot_2018-03-05_08-13-10](https://user-images.githubusercontent.com/202757/36961799-2f041f7e-204d-11e8-80a7-4d0b80a99b09.png)

## Searching for `ads` only shows cookies that contain the term (and only name, not value)
![screenshot_2018-03-05_08-13-32](https://user-images.githubusercontent.com/202757/36961800-2f1ce608-204d-11e8-84f3-3f744b8fc3d5.png)
