### ISSUE TITLE
Won't compile with Debian 9

### ISSUE THREAD

**Issue by bmorel** [OtterBrowser/otter-browser#1564]
Hello.

I guess you do not intend to support Qt 5.7, which is the one in current Debian stable. However, I'm interested to try Otter on it anyway, so I tried to compile despite the fact my Qt version is too old.

I do not ask you to fix the things, nor to accept any patch I'll do that'll remove features (obviously... I'm trying to backport stuff, that won't make a shiny new software), I'm just asking for pointers on documentation I could not find myself so that I could try to build Otter with Debian's current libs.

Now that those things are said, here is the list of stuff I could not find documentation about:

For QtWebKit backend, it's mostly:

* file QtWebKit/QWebFullScreenRequest is not found, but I have a file named QWebEngineFullScreenRequest in my /usr, so I think I might tinker something without even remove the feature?
* QWebFullScreenRequest, nothing about it in my /usr/include, for now.
* no member named 'FullScreenSupportEnabled' in 'QWebSettings', but it's present in QWebEngineSettings, might be some hackish way around that.

* MessageLevel (Console::MessageLevel is being suggested);
* MessageSource;
* LogMessageLevel, WarningMessageLevel, ErrorMessageLevel from MessageLevel (the enums does not match exactly, wonder if those are compatible...)
* no member named 'consoleMessageReceived' in 'Otter::QtWebKitPage' this is about messages, again? What kind of messages?

* no type named 'setPluginSearchPaths' in 'QWebSettings' and now some plugin stuff. I could find something in Qt4.8's doc, but could not find it into the 5.7's one... Surely I missed something!
* no member named 'pluginSearchPaths' in 'QWebSettings', I'm almost certain it's related.

It seems like some of those problems are about APIs that are only present in one engine but not the other one... might find some work around, or not, but it's worth a try (well, at least, I'll have some fun trying).

For QtWebEngine (here, I could find documentation, but maybe you could give some opinion on those points?):

* no member named 'save' and 'print' in 'Otter::QtWebEnginePage'. There is, however, a "load" function that is said to have been in a different component, I might work around for degraded feature, which seems to "just" be printing and saving files anyway. Might be wrong about the save, though (and a little about print too, of course).
* incomplete type 'QWebEngineDownloadItem'. I could find it, so this must be an include problem somewhere. Hopefully it does not hide too many trees.
* unknown type name 'QWebEngineHttpRequest': this seems to be the most problematic thing for QtWebEngine, there are http stuff, but the name patterns don't match a lot...

**Comment by Emdek** [comment]
@bmorel, we support Qt 5.6 and newer (since it's the last LTS that supports XP), but... we don't support legacy QtWebKit anymore (anything older than 5.212 is based on WebKit branch from 2013, or even older).
QtWebEngine is similar story (5.7 is based on very old Chromium version, unless maintainers backport a lot). Moreover, QtWebEngine has very limited public APIs comparing to QtWebkit, so enabling new *basic* features (like... printing) requires newer versions (usually we keep compatibility with previous LTS, which was 5.9 anyway).

There are several solutions for your case:
- update your QtWebKit package to 5.212 (there might be some unofficial packages somewhere, you can also try building from source);
- build against binaries from official Qt SDK paired with QtWebKit 5.212 binaries;
- wait for our AppImage (we are working on solving OpenSSL 1.0 vs. 1.1 incompatibility).

AFAIK all major distributions switched to 5.212 last year, but Debian stable is special case. ;-)
