### ISSUE TITLE
Please re-prioritise the TODO list

### ISSUE THREAD

**Issue by RJVB** [OtterBrowser/otter-browser#1651]
Looking at the major things planned in the TODO list I think the priorities could be improved. For instance, implementing a safe password storage backend isn't even on the list while it should be up very high. And as far as I'm concerned this should apply to web extension support too; surely I'm not the only one who thinks that would be much more desirable than having support for tab grouping or a helper for mouse gestures...?

BTW, if proper web extension support is too tricky/cumbersome, how about support for Greasemonkey scripts (and/or something that helps the user figure out why a supposedly supported add-on  doesn't work)?

**Comment by Emdek** [comment]
@RJVB, that file doesn't decide what gets implemented first, it's more like a loose list, updating it right now is pointless.
The issue is lack of man power, we need more developers.

BTW, tab grouping is VERY important for me, and the main blocker was always issue with styling (keeping it consistent with platform style).
