### ISSUE TITLE
Explain somewhere which kind of engine is used?

### ISSUE THREAD

**Issue by matkoniecz** [OtterBrowser/otter-browser#1682]
to start: it is request for more documentation, feel free to close it if you are expecting people to dive into code or look for documentation posted somewhere but not linked from readme (this is also perfectly viable approach especially as people most likely to actually contribute will likely be capable of getting this info from the source).

Is it reusing Chrome rendering engine? Can it reuse both Firefox and Chrome rendering engine? 

After reading README I see only 

> We also use JavaScript for interacting with rendering engines

and maybe I missed but I see no pointer to more advanced architecture overview. In theory I can read code but it is kind of overwhelming for obvious reasons.

**Comment by Emdek** [comment]
@matkoniecz, the issue is that right now there is nobody interested in writing the docs.
Two engines are supported and availability depends on build time flags:
- QtWebKit - default, based on quite outdated snapshot of WebKit;
- QtWebEngine - based on Chromium (exact version depends on Qt version in use).
That JS usage means that we can inject and execute code.

**Comment by JulianGro** [comment]
By the way, I am not interested in writing right now as well, but I maintain the Sphinx documentation for Vircadia and have that hooked up to Weblate. So if anyone wants use Sphinx and would like a maintainer for that (or someone to set it uo in the first place), call me interested.

**Comment by Emdek** [comment]
Related: #1181.
