### ISSUE TITLE
QtWebEngine backend not available on Windows release?

### ISSUE THREAD

**Issue by altPOCA** [OtterBrowser/otter-browser#1687]
QtWebkit is the default engine and there is no other options! I recall on Haiku OS version of Otter I could change between QtWebkit and QtWebEngine backend. Why it's not supported on the Windows release?

**Comment by altPOCA** [comment]
dead browser

**Comment by Emdek** [comment]
@altPOCA, you need to be more patient. ;-)
Availability of backends depends on build time configuration, there are no official two engine builds for Windows since it creates huge packages, this is why there are (usually, but not always) separate QWE builds in _experimental_ directory.
Also, QtWebEngine is still marked as experimental for a reason, in Qt 5.15 there were changes resulting in issues with context menu.
