### ISSUE TITLE
Consider Creating Flatpak for Easier and Wider Adoption

### ISSUE THREAD

**Issue by chrisdebian** [OtterBrowser/otter-browser#1740]
Hi, 

I'm loving the look of the Otter browser, but rather than have some official ways to install the application, and some unofficial ways, would it be possible to consider having a Flatpak available?

I'm sure you'll be aware of Flathub https://flathub.org/home, and the way to have an application listed on the site, can be found here https://github.com/flathub/flathub/wiki/App-Submission

Making a Flatpak available, will ensure that a greater number of users have the most up to date version that you release.

Many thanks,

Chris
chris_debian

**Comment by asctime** [comment]
May I ask, what platform did you have flatpack in mind for? Otter-browser already compiles OOTB on most qtweb platforms. Flatpack is good when requirements and configuration are head-spinningly complex or over-demanding for normal users, but I really don't see that as the case here. The evil side of flatpack is it becomes a huge crutch and facilitates unnecessary bloat for what is otherwise a highly efficient and streamlined package. Can you please clarify?

**Comment by Emdek** [comment]
@chrisdebian, see #1148, not much changed since, other than less manpower available for the project…
So unless someone will volunteer, then there is no option for expanding provided package types, since there is an issue with creating any packages right now.

**Comment by faveoled** [comment]
I have a working Flatpak [here](https://github.com/faveoled/org.otter_browser.OtterBrowser).
The last stable version can't be published to Flathub because file downloads use /tmp location by default instead of the one provided by the user. This has to be changed if someone wants the app to be on Flathub
