### ISSUE TITLE
Improved behavior of the address bar

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#224]
For now when open the link in a new tab text in the address bar appears only when the first data starts download (how I understand. In any event, are not always immediately). If the connection to the server is very slow, the text does not appear immediately. Need to do it to appear immediately after opening the tab.

**Comment by beastie1** [comment]
I don't remember when exactly this happened, but all the fixes made in this issue have been reverted back.

So like before, if the connection is not fast enough and you stop the loading of the tab, Otter will end up with an empty address bar.

This happens when loading a new tab in the foreground or in the background, or through tab cloning.

**Comment by beastie1** [comment]
I'm sorry to bug you again with this bug!

It seems there's one last case where this problem occurs, and that is with **target="_blank"** links.
