### ISSUE TITLE
Customizable toolbars (JSON file)

### ISSUE THREAD

**Issue by lollox** [OtterBrowser/otter-browser#31]
OK, this is really important.

Is it planned to have a complete customization system like in the good old Opera? ... here is it what I mean:

- .ini files to control all the GUI elements (toolbars, menu, mouse, keyboard, etc) that can be edited 
- support (in the .ini) for custom commands and chain of commands to create our own buttons and menu items
- moving all buttons and toolbars everywhere (you want even the address filed on the side? you get it, and so on :D ) without any limitation

Thanks in advance :D

**Comment by Emdek** [comment]
One more detail, property for visibility has to be three-state, so we can auto hide toolbars too (for example tabbar, when there is only one tab, but defaulting to always visible).

**Comment by ersi-dnd** [comment]
"Show tabbar" option should be sticky, i.e. when I want tabbar off, it should stay off across app restarts. 

And every toolbar should have an on/off toggle like tabbar and menubar. Plus there should be a toggle/action/scriptlet to switch off all toolbars, leaving only window decorations.

Is this part of this ticket?

**Comment by Emdek** [comment]
@ersi-dnd, most of it.
I'm not sure about action to hide all toolbars, but sooner or later it should be doable as part of APIs for extensions.

**Comment by ersi-dnd** [comment]
There are several reasons why I want to toggle toolbars on and off both individually and them all collectively.

- There should be more access and management options for tabs anyway, for example a menu that lists all open tabs, corresponding to Opera's Internal Window List; I used to have it available as a menu in the menubar and as a section in the tray icon right-click menu
- It makes sense to turn off a bookmark bookmarks bar, statusbar or a custom toolbar; the same option should be available for any toolbar
- Opera had such toggle actions individually for each toolbar, collectively for them all, and for any combination of them by means of serialising the relevant actions in toolbar.ini
- Anticipating the arrival of true detach, which should basically be a window without any toolbars, just the content, I hope to be able to turn off all toolbars, including menubar, quickly and easily even without detaching; to turn off tabbar so that it stays off would be a nice start in that direction

**Comment by beastie1** [comment]
I don't know if memory is failing me, but I remember we once talked about enabling/disabling the status bar, which is just like any other toolbar. So adding **Show Statusbar** to **View > Toolbars** seems like a good idea.

Also I think the entries in a custom **toolBars.json** file should be loaded into **View > Toolbars** so that we could enable/disable custom toolbars.

**Comment by Emdek** [comment]
@ersi-dnd, that action was just for hiding or it could also bring back just these toolbars (and only these which got hidden in the first place)?

@beastie1, it will be reworked that way as soon as we will start to write values back to that file.

**Comment by ersi-dnd** [comment]
@Emdek *that action was just for hiding or it could also bring back just these toolbars (and only these which got hidden in the first place)?*

The actions to toggle a toolbar looked like this in INI

`F11 alt = Enable menu bar | Disable menu bar`
`F7 ctrl	 = Enable scroll bars | Disable scroll bars`

In your case, I think it makes sense to create a one-line toggle to switch toolbars both on and off with a single action. Because, for example, you never create one action to enter fullscreen and another to leave it, do you?

**Comment by Emdek** [comment]
@ersi-dnd, yeah, in case of fullscreen it's a single toggle action, such approach makes sense in most cases.
I was just curious if it was something more flexible or more "hardcoded", and since it lists toolbars by name it can be considered the latter.

**Comment by ersi-dnd** [comment]
@Emdek 
Yes, it's pretty mechanical - hiding all the toolbars occur by simply combining the actions with the toolbar names into one command, but there are two subtleties that I would like to point out. I hope I can make this clear.

*Nuance 1 - Customised fullscreen*

Since the user was able to combine actions as I have described so many times, the user was able to create a customised version of fullscreen by doing for example
    Enter fullscreen & Enable menu bar
i.e. by combining fullscreen with any toolbar(s) of his choice. 

Of course, when you wanted an extraordinary custom toolbar in fullscreen that you didn't want in normal mode, `Leave fullscreen` had to be modified similarly, to hide the custom toolbar when entering the normal mode. Not quite flexible, but perfectly customisable when you knew what you wanted. 

The best solution here would be to offer Fullscreen and Normal mode as separately customisable interface modes a la VLC. It would be a bit of an overkill for me personally (all I want right now is for the tabbar to be gone *totally* in fulscreen, not even appearing when I move the mouse to screen edge), but surely you can see the user potential in this kind of customisation of fullscreen view. No other browser has this as far as I know. 

*Nuance 2 - True detach*

Now, if you ever implement True detach, then understand that True detach *is* a separate interface mode. True detach is meant to be this: Drag away a tab to make it a separate window, but the window has only the desktop environment decorations, no toolbars. A webpage in old Opera, detached by True detach, only preserved the address toolbar, nothing else. Statusbar and menubar disappeared. Other windows behaved similarly. 

The essence of True detach is this: Think about how the tab would appear inside the window, if it were unmaximised or cascaded, e.g. like in the picture 
![pegasus-mail-1](https://cloud.githubusercontent.com/assets/6865273/6852573/205c75b0-d3ee-11e4-9b14-a7f750aecce4.jpg)
When detached, this is how the tab should appear outside the window too - the "global" toolbars gone.

The exact point I want to raise in this context is that it would be nice to have a simple one-command action that would cause an existing window to assume the True detach mode, i.e. 

- When the window has a single tab open, running the action would make it lose the excess toolbars as in True detach
- When the window has multiple tabs open, running the action would perform True detach on the focused tab.

Something like this available in DWB browser - not the detach, but the command that hides all toolbars. Otter should have that with the detach. 

Oh, and anyway, by True detach I of course mean that this should be the only way to detach tabs. There should not be two detaches. True detach is the one and only meaningful detach. This is how Opera originally worked when I got closer familiar with it at v.6.

**Comment by lollox** [comment]
> True detach is the one and only meaningful detach just like proper fullscreen is the one and only proper fullscreen.

Isn't this against the customization spirit Otter should have? I mean, I've no problem with the detach you describe, but I don't see why, once the "commands model" you described above is implemented (that is a must for me, since without the ability to combine commands as in the old INI files all my customization thoughts will die soon), users should not be able to choose how their tabs and windows should behave

**Comment by ersi-dnd** [comment]
What choice will go missing, in your opinion?

Another argument in favour of True detach is that, when implemented, Otter will be unique. True detach is something Opera used to have but dropped along the way to become more similar to other browsers, losing its uniqueness.

**Comment by Emdek** [comment]
@ersi-dnd, I'm considering special attribute per toolbar to decide visibility in fullscreen mode (hidden, auto, visible), the only complication is *auto*, to make them behave like Tab Bar right now.

About true detach, according to this description it worked as if instance of ``Window`` (widget that contains single tab - navigation bar and ``WebWidget``) was simply set to be top level window.
That approach would be easier to do but there is one catch, there must be instance of ``MainWindow`` around (to handle shortcuts etc.), and when main window gets closed then all sub elements get closed too.

**Comment by ersi-dnd** [comment]
Not sure if I understand the *catch* properly, but in Opera there was a catch too, which is one of the reasons why True detach was removed: 

When the user (1) detached a tab, then (2) closed the main window, then (3) closed the detached tab, and (4) the startup setting was "Continue from last session", then at next startup the user would be faced with the detached tab, no menubar or any other global toolbar. Those who didn't know the keyboard shortcuts would panic because they didn't know how to get the normal window back. 

Instead of removing the feature, there were several right solutions to this problem.
1. With "Continue from last session" enabled, spawn the lastly used main window together with the last detached tab.
2. Spawn the last detached tab as a full-blown window with global toolbars.
3. Instead of continuing from last session, show the startup dialog (sessionchooser) where the user can choose whether to shoot up a new session with a new fullblown window or indeed proceed with only the detached tab.

True detach was ingenious because it was a useful user case. When it was removed, users began to replicate it in various ways, but it was always a tedious workaround, not a simple ingenious feature anymore.

If I understand your catch correctly, then permit me offer two ideas to work it out:

1. Instead of making instance of `Window` top level (assumingly allowing main window to be closed), only allow the main window to be minimsed in the background, never closed, so that all keybinds etc would remain operable. 
2. Instead of creating True detach based on top-level `Window` as you seem to be thinking now, work it out on the basis of everything that goes into a proper new window. It would be the kind of detach as it is now - which works okay as far as it goes - but make it lose the global toolbars when detached.

**Comment by Emdek** [comment]
@ersi-dnd, the easiest approach is to simply require parent ``MainWindow`` to be around and close such detached tab when parent is closed.
Simply it would be just like part of ``MainWindow``  but without being restricted to exist inside MDI area.
In worst case scenario it would result in session with MainWindow without tabs (but still visible) and separate ``Window``.

The only real issue here is that it won't be obvious that closing ``MainWindow`` would close ``Window`` too (that could be solved by hiding ``MainWindow``, but it's not really obvious and complicates some stuff) and it wouldn't be easy to guess which Window belongs to which ``MainWindow`` if there would be multiple detached tabs of multiple main windows.

But since such option wouldn't be default anyway then it shouldn't be big issue for end users.

**Comment by ersi-dnd** [comment]
To be honest, I'd only be fully satisfied with a solution that allows closing the main window, but I understand if it's too difficult to do. 

The ordinary user case for True detach for me is this: I open up Flash player on a webpage, detach it (i.e. everything browser-related must go away, leaving just the player), and the other thing I need is a text editor to take notes, so I switch between the text editor and the player. 

For this, the best would be the ability to close the main window in the background, but it will be okay when you make main window at least minimisable. (I'd also like the background window to be properly accessible when a prompt or dialogue is up. There are user cases for that, e.g. when editing a bookmark item, which is a dialogue, the user would like to copy a URL or description from the main window in the background.)

As to your fear that there could arise confusion about what detached tab belongs to which main window, I suggest you to implement Windows Panel in a properly structured way, so everybody can look there to sort out the hierarchy and (re)order everything by dragging.

**Comment by Emdek** [comment]
@ersi-dnd, sure, we can discuss details later.
BTW, #190 is more suitable place to discuss this, or new ticket. ;-)

**Comment by ersi-dnd** [comment]
I just had an idea concerning the relationship of True detach and Main window: Hide is not implemented! 

If Otter can be hidden, i.e. if "Hide Otter" gets implemented, then 

1. "Close main window" could simply hide the main window when a Detached window is open. 
2. When the last Detached window gets closed, the main instance would close too.
3. "Continue from last session" would respawn the last Detached window with the main window.

**Comment by Emdek** [comment]
@ersi-dnd, you can hide all windows when tray icon is visible, without there would no way to restore them in clean way.

**Comment by ersi-dnd** [comment]
You mean you have Hide as a menu item in tray icon, but it won't be available as action for keybind? And what I described is not doable?

**Comment by Emdek** [comment]
@ersi-dnd, yes, first item in context menu of tray icon.
We can't allow to use it without global shortcuts which aren't available...

We can discuss that later, right now there are too many other tasks for beta. ;-)

**Comment by Emdek** [comment]
There might be still some rough edges but this feature is now fully usable.

**Comment by beastie1** [comment]
One of the biggest achievements of this project IMO.

I like the customization menus. They're better than Opera's.

Great job! Thanks.

**Comment by Emdek** [comment]
@beastie1, there are plans to redo it to be more like in Firefox (which can be considered vastly improved variant of UI from classic Opera, well, at least most of the aspects got improved ;-)), with special page with all contents presented in more user friendly way (more visual, with grouping).
Menus most likely won't change much and dialog will be still available (maybe splitting it to two tabs, options being default one), but default mode to change arrangement will be drag and drop.
