### ISSUE TITLE
'debian' packaging instructions

### ISSUE THREAD

**Issue by landroni** [OtterBrowser/otter-browser#43]
Is there a 'debian' packaging dir available? I see that you provide Debian packages for the current releases, but I cannot see the 'debian' dir anywhere in the sources.

**Comment by xtaran** [comment]
So to build the Debian package, the intended commands are these?

```sh
mv packaging/debian ./
dpkg-buildpackage
mv debian packaging/
```

I'm sorry, but putting the `debian` directory anywhere else than in the root directory doesn't make much sense as that's the specified location and no tool will work with it if it's anywhere else. If you don't like it there, put it in a separate packaging branch and merge in the master branch regulariy (usually with each release).

**Comment by landroni** [comment]
It usually is an issue when the 'debian' dir is part of the root dir (where it should be for packaging), since upstream 'debian' may not be the one used by distros. Distros tend to modify the scripts to suit their needs, and won't use the upstream 'debian' but for the first packaging effort. In my opinion this is precisely what the upstream 'debian' dir is useful for. If you want to use it as is, then indeed the sequence above will help.

**Comment by xtaran** [comment]
> It usually is an issue when the 'debian' dir is part of the root dir (where it should be for packaging), since upstream 'debian' may not be the one used by distros

I don't know any tool where this is an issue. As far as I know all Debian packaging tools which are handling upstream tar balls (e.g. `dpkg-source`, `gbp import-org`, etc.) ignore `debian/` directories in the upstream tar ball for exactly these reasons.

Anyway, thanks for the feedback and explaining the reasoning behind this decision.

**Comment by Frenzie** [comment]
@xtaran Welcome, it's nice to see such a seasoned Debian developer around! Besides what @landroni said, isn't it exactly the same with `PACKAGE/debian` in lynx? Which is not to say I wouldn't like to see `debian/` in the root dir, but then I'm a Debian user… :-) Anyway, while I would like to think I've come fairly close to identifying the necessary steps toward a proper Debian package (see [here](https://github.com/Frenzie/otter-virtual-build-environment/blob/master/debian/scripts/build-otter-deb.sh); it generates a .orig.tar and all that), I think that at least for the moment it's also primarily a helpful hint to potential maintainers (such as perhaps myself) rather than a properly finished and maintained aspect of Otter.

**Comment by xtaran** [comment]
> isn't it exactly the same with PACKAGE/debian in lynx?

I don't know. And I maintain the Lynx package for Debian. :-)

But actually you made me aware of why I'm wondering about this stuff: otter-browser isn't packaged for Debian yet while Lynx is. So I don't care for where Lynx upstream has his packaging...

Nah, with Mozilla wanting to get rid of XUL (and hence kicking my favourite browser [conkeror](http://conkeror.org) in the ass), I feel forced to look around for alternative free browsers for the future. And since I was a heavy Opera user many years ago... :-)

**Comment by landroni** [comment]
"I don't know any tool where this is an issue. " 

From memory in emelFM2 previously the source included a 'debian' dir in the expected location, and it conflicted/interfered with default maintainer setups in Debian. This lead to the folder being renamed to 'debian-unofficial', which is still in current master. This is why I suggested keeping this dir outside the expected location: manual installations/handling can move the folder to the expected location, whereas distro maintainers don't need to work around this.

**Comment by xtaran** [comment]
Hi,

On Fri, Jan 15, 2016 at 05:40:42AM -0800, landroni wrote:
> "I don't know any tool where this is an issue. " 
> 
> > From memory in emelFM2 previously the source included a 'debian'
> > dir in the expected location, and it conflicted/interfered with
> > default maintainer setups in Debian. This lead to the folder being
> > renamed to 'debian-unofficial', which is still in current master.
> > [...] distro maintainers don't need to work around this.

Thanks for getting more detailed. I guess I now know where our
different views come from:

In the past, for the old debian source package format ("1.0") this was
indeed an issue.

But with the "3.0 (quilt)" source package format which is use for many
years now, this is no more an issue. I'm so used to the new format,
that I forgot many of the not so obvious drawbacks of the old format.

And your packaging in packaging/debian/ is already source format "3.0
(quilt)". Good. :-)

https://wiki.debian.org/DebianMentorsFaq#What.27s_wrong_with_upstream_shipping_a_debian.2F_directory.3F
still has the reasoning why Debian didn't like that in the past, so
this clearly confirms your argument. But it also states that this no
more the case with modern packages.

		Kind regards, Axel
-- 
/~\  Plain Text Ribbon Campaign                   | Axel Beckert
\ /  Say No to HTML in E-Mail and News            | abe@deuxchevaux.org  (Mail)
 X   See http://www.nonhtmlmail.org/campaign.html | abe@noone.org (Mail+Jabber)
/ \  I love long mails: http://email.is-not-s.ms/ | http://abe.noone.org/ (Web)

**Comment by landroni** [comment]
@xtaran 

Thanks for sharing this. I haven't tested it in a while, but I believe that as soon as there is 'debian' folder in the usual location in the source archive, replacing it will make Debian packaging tools confused. Even with 3.0 standard. From memory, on Ubuntu this may result in resulting packages being coded as "native debian package" (whatever that means), which isn't the Ubuntu packaging way. I may be wrong.
