### ISSUE TITLE
In-line spell checking

### ISSUE THREAD

**Issue by brcontainer** [OtterBrowser/otter-browser#504]
The Otter is not supported for spellchecker?

**Comment by ersi-dnd** [comment]
Plz somebody fix the title, so this ticket shows up in relevant searches. Thanks!

**Comment by Emdek** [comment]
@ersi-dnd, I guess that it was result of missing support for it. ;-)

It seems to be doable (at least for *QtWebKit*) by use of ``QWebSpellChecker`` from undocumented but semi-public (not shipped as private but with warning that it is not public API, odd) *qwebkitplatformpkugin.h*.
*Hunspell* seems to be the best candidate to be the backend.

**Comment by VSHY** [comment]
Hunspell is good.

A small but important wish: I would like to be able to turn on several dictionaries (languages) to spell checking at the same time.

**Comment by Emdek** [comment]
@VSHY, this might be doable, although no promises yet.

**Comment by VSHY** [comment]
@Emdek 
Something similar is done @FeyFre for AkelPad, but he used Aspell.

**Comment by beastie1** [comment]
So you didn't choose Hunspell for spell-checking?

**Comment by Emdek** [comment]
@beastie1, Sonnet uses it as one of plugins, so there is high chance that it will be used.
Also I'm considering use of bundled version of it, simplified to be just a high level wrapper over Hunspell.

**Comment by beastie1** [comment]
```
$ cmake ../
CMake Warning at CMakeLists.txt:70 (find_package):
  By not providing "FindKF5Sonnet.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Sonnet", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Sonnet" with
  any of the following names:

    KF5SonnetConfig.cmake
    kf5sonnet-config.cmake

  Add the installation prefix of "KF5Sonnet" to CMAKE_PREFIX_PATH or set
  "KF5Sonnet_DIR" to a directory containing one of the above files.  If
  "KF5Sonnet" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by PStokman** [comment]
How does one enable the spellchecking any way? Does Otter need to be compiled with Sonnet libraries and added as dependencies? I can't get it to work, I see the options but they're disabled. Using the Ubuntu PPA weekly builds and haven't seen any change in dependencies.

The release notes mention that it isn't available for Windows, but it would be nice to have information on how to get it to work on Linux.

**Comment by midluk** [comment]
I noticed that I have enabled spell checking (and selected a dictionary) in the right click menu of this comment edit box, but it does not seem to do anything. I have installed sonnet and hunspell (and the list of  dictionaries seems to be what is really installed).
In the notes (my default "I write text here because your f***ing contact form only shows 15x3 characters"-place) there is no spell checking available at all from the right click menu.

**Comment by Emdek** [comment]
@PStokman, yes, Sonnet headers must be available at compile time, it will be enabled if CMake will be able to find it.
The plan is to bundle modified version of Sonnet since its availability is limited and its API is not flexible enough (like hardcoded search paths for dictionaries which is show stopper for Windows) which will allow to depend directly on Hunspell (which is acceptable as dependency).

**Comment by PStokman** [comment]
@Emdek, can you (or the person who maintains it) change the build process for the Launchpad PPA packages for those of us that use them and are not comfortable building packages themselves? I would appreciate that a lot. You're making one great program and I use it as my default browser. It's amazing how stable it already is.

**Comment by Emdek** [comment]
@PStokman, I'm hoping to get that bundling done soon, but sadly I'm constantly busy with other stuff recently. :-/
Changing it to use Sonnet as hard dependency has two big issues:
* some people not using KDE5 don't want to see such libraries being required,
* it is not available in older versions of Ubuntu anyway.

**Comment by PStokman** [comment]
Yeah, that is the biggest drawback at the moment. On one system I use KDE, but on the others I don't. If I have to pull in a lot of KDE libraries for spell checking, then I'm OK with that because Otter is worth it. But if a different method could be used, like how LibreOffice does it, that would be really cool.

Perhaps make a second build job for only the releases that are capable and give it a slightly different name, like the daily builds that have '-git' at the end.

Other stuff can be important too. Do what you feel is best. :)

**Comment by beastie1** [comment]
> some people not using KDE5 don't want to see such libraries being required,
Indeed.

> it is not available in older versions of Ubuntu anyway.
Or FreeBSD ...

**Comment by beastie1** [comment]
Could you add **Q_OS_FREEBSD** in **/3rdparty/sonnet/src/plugins/hunspell/hunspelldict.h** please?

FreeBSD uses /usr/**local**/share/... paths.

**Comment by Emdek** [comment]
@beastie1, thanks for suggestion, although I've used a bit different approach, since I'm going anyway for list of search paths and this one used by FreeBSD could be used by others too, it's now checking for it always.

**Comment by PStokman** [comment]
Today I rebuild the package in the Ubuntu PPA with hunspell dev headers (and libkf5sonnet-dev) using the simple example noted in the debuild manpage, debuild -i -us -uc -b (and some help from http://www.debian-administration.org/article/20/Rebuilding_Debian_packages), and it provided the wonderful spell checker.

I have to say, the dependencies for sonnet-plugins is minimal, just the libkf5sonnet packages and those are just 3 extra. There are no additional KDE packages pulled, at least on Debian.

@Emdek, can you reconsider letting the Ubuntu PPA packages be build with sonnet support? If not, I just rebuild the packages myself. Only need to figure out where the version is noted for the package, so the repo one doesn't replace my own when looking for updates.

**Comment by PStokman** [comment]
I rebuild the new weekly, beta11 weekly 125 and this time I had the sonnet-plugins and libkfsonnet packages removed. Obtained the build-deps, which include libhunspell-dev, and the result was a working spellchecker. This is also reflected in the dependencies of the rebuild package. However, the PPA packages doesn't depend on hunspell at all.

@Emdek 
Can you poke the PPA maintainer to include libhunspell-dev in the build procedure? Or can/should I contact him/her?

**Comment by midluk** [comment]
On Fedora the hunspell dictionary packages install dictionaries to "/usr/share/myspell/"
Since I added that path to the directories list in hunspellclient.cpp I finally have spell checking working.

**Comment by midluk** [comment]
OK, there are still a few problems (with today's git master on Fedora 23 x86_64):
1.  Spell checking seems to be not implemented for notes

2. Default selection of dictionaries is not working correctly
When starting otter I get "Warning: No language dictionaries for the language: "en-GB" ((null):0, (null))".
I have the LANG environment variable set to en_GB.UTF-8 . 
The selected dictionary in the right click menus is "American English (United States) [GB]", when I select "British English (United Kingdom)" I get working spell checking.
Given that my dictionaries have file names like "en_GB" (with underscore) instead of "en-GB" as given in the message, this might be the problem.

3. The manual dictionary selection is not remembered when opening new tabs or restarting otter

4. Sometimes spell checking seems to stop working completely regardless of dictionary selection

**Comment by Emdek** [comment]
@PStokman, I've finally managed to add it to daily builds, it should be already in others for some time.

@midluk, Sonnet is way from being perfect...
I could try to improve it but it seems to be waste of time, QtWebEngine has own built-in system (it was supposed to debut in Qt 5.7 but get postponed, custom dictionary format invented by Google causes issues) and revived QtWebKit should get own built-in system soon too (AFAIR it would be based on *enchant*).

The best solution for remaining uses cases (other widgets that could make use of spell checking, like notes editor) would be upstream spell checking addon from Qt developers, something with sane API.

**Comment by PStokman** [comment]
@Emdek, thanks, but did you also add it to the weeklies? That's the one I use and it doesn't have hunspell as dependency whereas the daily build, otter-browser-git, does. I'll see it on Thursday, when the new weekly build is usually available.

**Comment by Emdek** [comment]
@PStokman, it is listed in *control* file as dependency, so it should get enabled.

**Comment by PStokman** [comment]
@Emdek, I know. When I do an apt-get build-dep otter-browser (with the weekly PPA as source), libhunspell-dev gets installed. But the package there has the following information:
```
Version: 0.9.11-dev127-1~vivid~ppa1
Recommends: gstreamer0.10-plugins-base, gstreamer0.10-plugins-good
Depends: libc6 (>= 2.14),
libgcc1 (>= 1:4.1.1),
libqt5core5a (>= 5.4.0),
libqt5dbus5 (>= 5.0.2),
libqt5gui5 (>= 5.3.0) | libqt5gui5-gles (>= 5.3.0),
libqt5multimedia5 (>= 5.2.0),
libqt5network5 (>= 5.3.0),
libqt5printsupport5 (>= 5.0.2),
libqt5qml5 (>= 5.0.2),
libqt5webkit5 (>= 5.2.0),
libqt5widgets5 (>= 5.3.0),
libqt5xmlpatterns5 (>= 5.0.2),
libstdc++6 (>= 4.9)
```
As you can see, no hunspell. So I just rebuild it with libhunspell-dev installed, then it gets added as dependency properly. Looking at otter-browser-git, the daily build, it shows as follows:
```
Version: 0.9.99~git20160612+r8~ubuntu15.04.1
Recommends: gstreamer0.10-plugins-base, gstreamer0.10-plugins-good
Depends: libc6 (>= 2.14),
libgcc1 (>= 1:4.1.1),
libhunspell-1.3-0 (>= 1.3.3),
libqt5core5a (>= 5.4.0),
libqt5dbus5 (>= 5.0.2),
libqt5gui5 (>= 5.3.0) | libqt5gui5-gles (>= 5.3.0),
libqt5multimedia5 (>= 5.2.0),
libqt5network5 (>= 5.3.0),
libqt5printsupport5 (>= 5.0.2),
libqt5qml5 (>= 5.0.2),
libqt5webkit5 (>= 5.2.0),
libqt5widgets5 (>= 5.3.0),
libqt5xmlpatterns5 (>= 5.0.2),
libstdc++6 (>= 4.9)
```
Hunspell is a dependency there. So no matter what's in the control file, if the build environment does not contain all the dependencies and the build doesn't fail, it doesn't note them afterwards. That's the current problem with the weekly builds.

**Comment by Emdek** [comment]
@PStokman, well, I'm not an expert on topic of PPAs...
Lets see how this week builds will turn out, if issue will remain I can try to analyze it further.

**Comment by PStokman** [comment]
New weekly arrived early this week, but still no hunspell as dependency.
```
Version: 0.9.11-dev128-1~vivid~ppa1
Recommends: gstreamer0.10-plugins-base, gstreamer0.10-plugins-good
Depends: libc6 (>= 2.14),
libgcc1 (>= 1:4.1.1),
libqt5core5a (>= 5.4.0),
libqt5dbus5 (>= 5.0.2),
libqt5gui5 (>= 5.3.0) | libqt5gui5-gles (>= 5.3.0),
libqt5multimedia5 (>= 5.2.0),
libqt5network5 (>= 5.3.0),
libqt5printsupport5 (>= 5.0.2),
libqt5qml5 (>= 5.0.2),
libqt5webkit5 (>= 5.2.0),
libqt5widgets5 (>= 5.3.0),
libqt5xmlpatterns5 (>= 5.0.2),
libstdc++6 (>= 4.9)
Filename: pool/main/o/otter-browser/otter-browser_0.9.11-dev128-1~vivid~ppa1_amd64.deb
```
The normal release, beta 10 at the moment, also doesn't have hunspell as dependency, but that could be because you haven't changed anything there yet.
```
Version: 0.9.10-1~vivid~ppa1
Recommends: gstreamer0.10-plugins-base, gstreamer0.10-plugins-good
Depends: libc6 (>= 2.14),
libgcc1 (>= 1:4.1.1),
libqt5core5a (>= 5.4.0),
libqt5dbus5 (>= 5.0.2),
libqt5gui5 (>= 5.2.0) | libqt5gui5-gles (>= 5.2.0),
libqt5multimedia5 (>= 5.2.0),
libqt5network5 (>= 5.3.0),
libqt5printsupport5 (>= 5.0.2),
libqt5qml5 (>= 5.0.2),
libqt5webkit5 (>= 5.2.0),
libqt5widgets5 (>= 5.3.0),
libqt5xmlpatterns5 (>= 5.0.2),
libstdc++6 (>= 4.9)
Filename: pool/main/o/otter-browser/otter-browser_0.9.10-1~vivid~ppa1_amd64.deb
```
As noted yesterday, the daily build (otter-browser-git) does have the proper dependencies. Don't know since when, I have to check one of my computers for that as they still have an older cache (but I'm not sure if I have the daily added).

Looking at the build logs of both projects, I do see libhunspell-dev getting installed, but the weekly has the following error:
-- Could NOT find HUNSPELL (missing:  HUNSPELL_LIBRARIES HUNSPELL_INCLUDE_DIR) 
And
-- The following OPTIONAL packages have not been found:
 * Hunspell (required version >= 1.3.0) , Generic spell checking support , <http://hunspell.github.io/>

Whereas daily shows this:
-- Found HUNSPELL: /usr/lib/x86_64-linux-gnu/libhunspell-1.3.so
-- The following OPTIONAL packages have been found:
 * Qt5WebKit (required version >= 5.4.1) , QtWebKit based backend (core) , <http://qt.io/>
 * Qt5WebKitWidgets (required version >= 5.3.0) , QtWebKit based backend (widgets) , <http://qt.io/>
 * Hunspell (required version >= 1.3.0) , Generic spell checking support , <http://hunspell.github.io/>

Makes me wonder, what is the difference between the two PPA build environments, what is in the code and how come it properly finds hunspell libraries in my build VM? Going to make a diff between the two source code build instructions in the DEBIAN directory.

**Comment by PStokman** [comment]
Got it! The problem is in the control file:
```
Source: otter-browser
Section: web
Priority: extra
Maintainer: Rog131 <samrog131@hotmail.com>
Build-Depends: debhelper (>= 9.0),
 cmake,
 libhunspell-1.3-0 (>= 1.3.3),
 libqt5webkit5-dev (>=5.1.0),
 libqt5xmlpatterns5-dev (>=5.2.0),
 qtbase5-dev (>=5.2.0),
 qtdeclarative5-dev (>=5.2.0),
 qtmultimedia5-dev (>=5.2.0)
Standards-Version: 3.9.6
Homepage: http://otter-browser.org/
```
```
Source: otter-browser-git
Section: web
Priority: extra
Maintainer: Rog131 <samrog131@hotmail.com>
Build-Depends: debhelper (>= 8.0),
 cmake,
 libhunspell-dev,
 libqt5webkit5-dev,
 libqt5xmlpatterns5-dev,
 qtbase5-dev,
 qtdeclarative5-dev,
 qtmultimedia5-dev,
Standards-Version: 3.9.5
Homepage: http://otter-browser.org/
```
Weekly says libhunspell-1.3.0, whereas Daily has libhunspell-dev. Without the development headers, it can't find the required files and thus builds without hunspell support. So all that's needed, is change the debian/control file for the weekly and releases project to make it match daily (except the package name).

While you're editing the control file, you might want to change the gstreamer version from 0.10 to 1.0. Otter already uses gstreamer1.0 as media backend and gstreamer0.10 is no longer maintained. In Debian, it's even removed from the repository, something that would likely also happen with Ubuntu 16.10.

**Comment by Emdek** [comment]
@PStokman, great, thanks. :-)
It should be fixed for next weekly.
