### ISSUE TITLE
Store and reuse authentication data

### ISSUE THREAD

**Issue by Peter2121** [OtterBrowser/otter-browser#509]
Hello,
I tested Otter on Windows and FreeBSD and I have the same issue on two platforms.
When I open a site with basic authentication required, the browser asks for the authentication every time I open a new tab or new window of the site. All other browsers (IE, Chrome, Chromium, Firefox, Midori...) reuse the login/password entered for the first page, but not Otter.
Please, correct this bug as I really like Otter and I would like to use it, especially for our Intranet sites.
Peter

**Comment by Emdek** [comment]
It seems that there might be another way, as once password is accepted then it is cached by Qt, so we could try to use some signal to notify other dialogs that they are no longer needed once first one gets accepted.

**Comment by Peter2121** [comment]
Tested 0.9.09 on FreeBSD - the problem is still present.

**Comment by PStokman** [comment]
Up till this day, with Weekly 118, it is still a problem (at least on Debian Unstable with Qt 5.5.1). I have resorted to use Konqueror to browse my intranet. Username and password are only stored for a single tab, instead of browser-wide. E.g. if you authenticate and close the tab, you should not have to enter your credentials again when you either restore the tab or open a new one on the same domain.

**Comment by vapaamies** [comment]
The same thing under Windows, Otter asks me password on every tab.

I have to use Otter for intranet, because used Opera since 2002 and cannot use other browser, but Opera 12.18 has problems with our intranet sites, unfortunately.

**Comment by Peter2121** [comment]
Tested on 0.9.12 - still the same problem.
Please, reopen the issue, the problem is NOT solved!!

**Comment by Emdek** [comment]
@Peter2121, we can consider it being superseded by #1141.
