### ISSUE TITLE
Harmonise sidebar and about: pages

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#569]
First, what I'd really want is of course more features into the sidebar, such as Notes and Links and Sessions and Tabs/Windows manager. But I'd also want a version of each about:page into the sidebar and vice versa - everything featured in sidebar to be expandable as an about:page. Here's what I mean.

![sidebar-button](https://cloud.githubusercontent.com/assets/6865273/5418536/b4f0b99c-824b-11e4-8474-78170b594e1f.png)
Notice the >> button next to x? Otter only has the x button on sidebar, while Opera used to have both. The >> button was dropped in Opera at some point, but I always kept it in my setup. This >> expanded every feature from the sidebar into a full page/manager.

Right now Otter has History, Bookmarks, and Downloads both in sidebar and as a complete about:page. Similarly, I think about:config, about:cache, about:cookies, Notes, Links, Sessions, Tabs/Windows and whatever other about:features will be implemented, they can have their own sidebar version. The >> button would open up the feature in the sidebar as a full page, just like in Opera.

**Comment by nacho20U** [comment]
fast please.

**Comment by lollox** [comment]
@Emdek 
> Currently sidebar uses exactly the same widgets as about pages

Is this a temporary solution? Because I think current panels widgets aren't very good since they need a lot of horizontal scroll (something that a panel shouldn't use at all instead)


I don't know how QT or QTQuick work, but how about a more fluid layout as "responsive design" in web or the "Modern apps" in Windows 10? maybe this could be the best solution if available :)

**Comment by Emdek** [comment]
@lollox, most likely these widgets will gain special mode to better fit sidebar, although it has low priority right now...
