### ISSUE TITLE
Ideas for Opera Turbo alike feature

### ISSUE THREAD

**Issue by lollox** [OtterBrowser/otter-browser#588]
Just for future reference, in case we'll consider to add a feature like Opera Turbo, here there is a good alternative that we could use for the purpose:

http://www.omgchrome.com/google-chrome-flywheel-data-compression-extension/

**Comment by Felipefpl** [comment]
If something like this is adeed i hope it will be as an extension, opera turbo or off-road mode in new opera i believe it's useless, it's reduce the quality of the images to load the page faster, this IS NOT optimization, it's deceiving and an insult to the intelligence of the ppl who needs this feature like me, a dial-up user. A tool to view the source and other stuff used by 0,2% of the ppl who use a browser would be better as extensions, this kind of thing only serves to BLOAT the browser and its memory consumption instead of improving it.

**Comment by lollox** [comment]
The world is FULL of browser "not bloated" in which everything you need is doable only through extensions (Chrome, Firefox, Opera, just to say the most famous)... So a project like Otter probably is not what you're looking for IMHO

**Comment by Emdek** [comment]
@lollox, well, the only non "bloated" browsers I know are text browsers and maybe OffByOne and Dillo. ;-)

So far I'm still suggesting direct use of caching proxies, as all such solutions make use of them anyway.

**Comment by lollox** [comment]
@Emdek : I'm not so "extremist" :P ... well, browsers I posted above are really not bloated... they give you an address field, back/arrow buttons, and what else? ... 

Consider that my message was not related to the "Turbo like" feature that to me may be implemented or may not since I never use it ;) (indeed I started the issue only for the sake of sharing that resouce I discovered :P )

**Comment by Emdek** [comment]
@lollox, well, there are no plans to bundle anything like that, and even if so, then it would be predefined entry (but not enabled by default) on list of available proxy servers or something like that. ;-)
Having it as predefined tool would require some kind of deal with service provider and that is out of scope anyway...

**Comment by Frenzie** [comment]
The ability to easily switch between multiple proxy servers is paramount for this functionality. Opera kind of dropped the ball there.

PS Low-quality images (that save like 90% of data traffic) is half the point of using Opera Turbo for me. You can always right click on a particular picture if you want the whole shebang.

**Comment by cattleyavns** [comment]
For performance benefit:
- Only compress image bigger than ??KB

Nice feature:
- Convert GIF to HTML5 MP4 video (reduce file size a lot)
- Compress image to black and white
- Maybe ability to compress video

You can take a look at Firefox Compression Proxy source code or Ziproxy.

**Comment by Emdek** [comment]
This feature is sort of out of scope anyway, since we don't have money to run proxy servers then we cannot offer such feature as built-in anyway...
But if someone knows some stable and free service that offers such feature then we could consider adding it to predefined set of proxies.

Related ticket for switching proxies: #785.
