### ISSUE TITLE
Online pdf reader

### ISSUE THREAD

**Issue by AlexTalker** [OtterBrowser/otter-browser#60]
Firefox included by default open source pdf reader(i think, project pdf.js). Please, included this feathure in browser.

**Comment by pierreporte** [comment]
According to the [Qt wiki](https://wiki.qt.io/Handling_PDF), there is a Qt widget named [XpdfWidget/Qt](http://www.glyphandcog.com/XpdfWidgetQt.html) (commercial license) that can be used to make a PDF viewer in Qt applications. There is also Poppler (under GPLv2) and some others. Since it is not PDF.js, it might be more secure.

**Comment by The-Compiler** [comment]
FWIW QtWebEngine is working on integrating pdfium (the Chromium PDF viewer).

**Comment by Emdek** [comment]
@pierreporte, it's fine as third party module, doesn't make sense to have built-in (and stuff provided by QtWebEngine doesn't count since it is backend specific).
