### ISSUE TITLE
64-bit Win 7 builds not running

### ISSUE THREAD

**Issue by komoku** [OtterBrowser/otter-browser#612]
64-bit builds of Otter do not run in my machines (two different machines) with 64-bit Win 7. They just fail silently, without any error message at all. In contrast, 32-bit builds run normally.

**Comment by justintimberland** [comment]
beta 4 still same issue

**Comment by komoku** [comment]
I have a machine where previous versions had this issue, and Beta 4 seems to work fine (note: not the same machine where I installed the VC++ redistributable the other day). So at least I can confirm it's fixed in some configurations...

**Comment by bajasoft** [comment]
@justintimberland, please try this version and let me know, if it works:
https://www.dropbox.com/s/sv4qzpz5az9gfti/otter-browser-win64-beta4-v2.zip?dl=0

**Comment by justintimberland** [comment]
Yes, this one works

**Comment by bajasoft** [comment]
The problem was in OpenSSL libraries where is hardcoded path to config file - it leads to drive where were this libraries installed on develop PC (G drive in all previous versions). It cause system exception in case there is drive with this letter, but it is inaccessible (like DVD drive without DVD).
