### ISSUE TITLE
Experimental backend for QtWebEngine (Blink)

### ISSUE THREAD

**Issue by Emdek** [OtterBrowser/otter-browser#615]
Qt 5.4 introduced initial version of QtWebEngine, which allows to use Blink rendering engine in Qt applications without additional effort.
While APIs are still very basic it is already possible to use it for web browsing (as long as you don't care about cookies, history, plugins, searching, caching, transfers, user agent, context menus and other stuff).
So we should start preparations to take advantage of that new Qt module by creating new, experimental backend (note that we will continue to support QtWebKit even when QtWebEngine will become mature), possibly adding some workarounds where possible (some stuff can be done using JavaScript, since it is possible to execute it from C++ even when it is disabled for webpage) and waiting for basic APIs to arrive in Qt 5.5 and 5.6 (note that there are no plans for *QNetworkAccessManager* integration, at least not for now - that integration would allow to reuse lots of code from QtWebKit, taking care of cookies, transfers, user agent, cache etc.).
Our APIs were designed for supporting multiple backends from beginning, the only missing part being configuration UI for selecting default one plus additional changes for loading backends as separate plugins (can be done later).
This backend would be build only when asked to by setting compile time option, it's important to note that it has higher requirements for compilers (it's an issue in case of 32 bit platforms, especially Windows).
It will be turned on when it will be become usable enough and later will become default one (QtWebKit may end up as being disabled by default), we could make it requirement for 2.0 milestone to have it fully functioning.
It would be nice to have initial version available for next milestone.

**Comment by Emdek** [comment]
So it begins. ;-)

This backend is disabled by default and requires command line option to be built (and Qt 5.4):
``
cmake -DEnableQtwebengine=ON ../
``
To set it as default backend you will need to set **Backends/Web** to *qtwebengine*.

Please note that this backend doesn't do much right now, it just loads pages and respects few basic options.

**Comment by billcreswell** [comment]
For my 2 cents, there are plenty of browsers using blink. Don't be them. Chrome, Vivaldi and Opera do that just fine.

**Comment by Frenzie** [comment]
Well, for my 2 cents Blink is the best Webkit: over the past year it actually managed to fix some Webkit issues that have annoyed me for almost a decade. ;)

**Comment by The-Compiler** [comment]
Yeah, QtWebKit might be removed from Qt source/binary distributions as early as the end of this year (Qt 5.6), so it's not really a question whether this should be done or not.

**Comment by haydara** [comment]
I have made small changes to the otter source code to make the default backend to qtwebengine when it is available since qtwebkit has been set to deprecated on Qt 5.5 see pull request:
https://github.com/OtterBrowser/otter-browser/pull/885

**Comment by Emdek** [comment]
@haydara, QtWebKit will be supported by upstream at least until 5.6, there is plenty of time, it's better to invest it into improving QtWebEngine backend or helping upstream. ;-)

**Comment by wblgrh** [comment]
I'm pretty disappointed over this. I get that if Qt will drop WebKit, then you have no choice but use Blink, but cannot you at least try to find an alternative solution before this happens? I don't care if Blink has the technical superiority over other engines, it's a freakin googel spyware...

I've chosen to wait for Otter, because it did not got in the line like the new "Opera" or Vivaldi or tons of other browsers; it is the only logical choice. Firefox is not an option, for that buggy snailware is useless and worthless...
Until this point i used Opera 12, because it is still the best browser. Of course i could stick with it for more time, but i don't know when the web will pass beside it ultimately... But now Otter seems to be mature enough to be a real alternative (for me at least) for the original Opera, so if Opera will become absolutely obsolete, i can change to Otter. (Unless it's using the Blink engine.)

So, you did a great job, i'm glad that i had faith in you and waited for Otter, instead of choosing something else.
Please don't screw up it now, by joining the g00gl mercenaries...

**Comment by The-Compiler** [comment]
@wblgrh I don't think there's any serious alternative. Do you have any sources for your claims about Chromium/Blink being "a freakin googel spyware"?

**Comment by wblgrh** [comment]
Nope, but google does nothing but spying on people, so whatever are they doing is effectively a spyware.

**Comment by The-Compiler** [comment]
Note Chromium is Chrome minus the google specific parts (see [differences between Chrome and Chromium](https://chromium.googlesource.com/chromium/src/+/master/docs/chromium_browser_vs_google_chrome.md)), and is completely opensource.

I don't like Google, quite the opposite - but if you're going to jump to conclusions not based on any factual evidence, then... there's little that can be done.

**Comment by wblgrh** [comment]
Look, i'm not denying, that i am paranoid if we're talking about google or microsoft, but is my paranoia about them is perfectly unfounded? Or maybe can be righteous? There is a saying, that being paranoid does not excluse the possibility of being persecuted...

While i concede, i have no proof, just suspicion; however, let's reverse the question: is there any proof about Blink being "clean"?
Opensource is one thing, but did you personally check the whole Chromium codebase? Line-by-line? A lot of people like to delude themselves of being protected from survelliance or hacking, just by using an opensource OS or browser. (No offense.) Opensource does not rule out the possibility of having malevolent code in the codebase.
I even can name an example for you: Android. Android uses Linux kernel, it's opensource and still, it's one of the most dangerous spy stuff ever created. (I believe, i don't have to prove that for you.)
And (not so) surprisingly Android is also a google product.

I may be wrong about Blink, but we cannot be sure, so my best guess is to play safe and avoid all (and i mean **ALL**) google stuff, including Blink. Or at least, have an alternative, just in case.
Just think about it rationally: if i were wrong, then Otter will have two (or more) web-backends, so what, is that a bad thing? But if i were right, then Otter can drop Blink at that instant and use an alternative backend.
Having blink as an *option* can be good (currently this is it), but having Blink as an only-choice is terrifying, for yet again, you have no choice, but google (this is what is planned).

I am aware that not everybody hate google or microsoft as much as i do and sometimes i demonise them too much, but thinking forward and leaving multiple possible directions open can be a lifesaver. (Figuratively speaking. Or maybe not entirely.)

**Comment by The-Compiler** [comment]
> Opensource does not rule out the possibility of having malevolent code in the codebase.

Of course it doesn't. The thing is, as far as security holes go, I trust an updated Chromium much more than I trust an outdated, unmaintained WebKit fork which never had the manpower it needed (QtWebKit).

I backported e.g. [this](https://codereview.qt-project.org/#/c/108936/) privacy fix from upstream WebKit to QtWebKit, and I'm sure there are other issues in QtWebKit yet to be uncovered, because it's a fork of a giant project with nobody watching security issues.

What you however *can* do is to observe what Chromium does as a black-box. Check file access (via e.g. SELinux/AppArmor), check traffic (e.g. using iptables), and then see if there's stuff you can't explain.

I did some quick search and found [this reddit thread](https://www.reddit.com/r/privacy/comments/34tc2f/how_safe_is_chromium_privacy_wise/). Some of those (like updating of extensions) are likely to not be present with QtWebEngine, as it uses a stripped down Chromium essentially.

> I even can name an example for you: Android. Android uses Linux kernel, it's opensource and still, it's one of the most dangerous spy stuff ever created. (I believe, i don't have to prove that for you.)

Again I believe you're mixing up Android with the (optional, proprietary) google addons. I know people who analyzed the network traffic (as part of the FSFE's [Free your android](http://fsfe.org/campaigns/android/android.html) campaign) of a free Android without Google addons. They found things like [this](http://www.phoronix.com/scan.php?px=MTYyODE&page=news_item) in Samsung images, but I'm unaware of anything they found in vanilla Android.

> if i were wrong, then Otter will have two (or more) web-backends, so what, is that a bad thing? But if i were right, then Otter can drop Blink at that instant and use an alternative backend.

You keep talking about alternative backends, yet you didn't present any alternative so far. I don't think QtWebKit is in the long run, for the security/manpower reasons outlined above, and because it'll be dropped from distributions for being deprecated at some point.

So, what alternatives are there? Are you going to maintain them? It's not like @Emdek can snip is finger and another backend - if there *is* any - is implemented and maintained.

**Comment by Emdek** [comment]
@The-Compiler, @wblgrh, there exist alternatives, but none of them is reliably enough to be usable on all platforms right now (like Qt bindings for Gecko, which most likely don't work under Windows and require compiling Gecko and in near future Servo might be worth to invest more time in researching it)...
But for now QtWebEngine is the only feasible option.

**Comment by wblgrh** [comment]
@The-Compiler, I did not "presented" any alternative, because i thought you know what are the alternatives.
But to name them, Otter could keep the outdated WebKit as an option, and i read about QtMozEmbed which is for embedding Gecko in Qt5 environment.
As for the rest, i think, it's futile to argue over it. If you disagree about google being evil and about that they should be avoided from the beginning, rather than examine their stuff if they are harmless or not, then i don't want to convince you.

@Emdek, Even if an alternative is not suitable for all platform, can you implement them per platform? For example, if that Gecko backend is available under Linux or BSD, then Otter could compile with it under Linux or BSD and could not compile with it under windows.

**Comment by Emdek** [comment]
@wblgrh, but it wouldn't by worth invested work, as nobody would package such big thing as modified Gecko just for us and almost nobody would like to compile something that big just to try it out...

**Comment by wblgrh** [comment]
So, basically you say, that Otter will only support those engines, which is supplied within Qt5?
What if Qt5 will never provide another backend, but Blink?

**Comment by The-Compiler** [comment]
> What if Qt5 will never provide another backend, but Blink?

FWIW the chances for that to happen are pretty good - QtWebKit got removed from the Qt 5.6 binary releases, and I don't think Qt is interested in maintaining *another* web backend :wink:

**Comment by Emdek** [comment]
@wblgrh, no, I didn't said that, but it is true that something that can be shared by multiple projects is the most feasible to use.

**Comment by wblgrh** [comment]
@The-Compiler, I can understand that they don't want to maintain multiple backends, but why does it have to be Blink...

@Emdek, So, there is a chance, that Otter will have a different backend than Blink. Okay, i'll wait for it. Currently, WebKit is the default in Otter, right? When will Blink become it?

**Comment by LimboSlam** [comment]
Hi there, this looks like a nice browser that respects user choice with lots of customization. But yes why switch to blink? It will only hold you back, well probably limit you as far as Blink/Chromium can go with flexibility and customization. I think this browser should, if re-based on a different engine, go with Goanna that is forked off Gecko which is used by Pale Moon (an Open Source web browser forked off from the Firefox/Mozilla code), another browser that focuses customization. 

Though this is just my opinion and I would be ok with it if all is applied up above.

By the way, whose the lead developer on this?

**Comment by The-Compiler** [comment]
Goanna (and Gecko) both aren't really designed to be used outside of Pale Moon/Firefox - from the [Goanna FAQ](https://moonchildproductions.info/goanna.shtml):

> Goanna does not have a stand-alone source, since it can't be used as a stand-alone library (maybe in the future, though...).

Why Blink/Chromium? Because QtWebEngine is the official upstream (Qt) successor for QtWebKit, well maintained by a decent developer base, and commonly packaged.

Integration of something not based on Qt might already prove difficult - and it's not feasible for @Emdek (or any other person really) to maintain their own fork of WebKit or Gecko.

This might work out more or less for Pale Moon - though ever there I think more developers are involved than there are in otter, and for them things are a lot easier: They could fork off Firefox, and have a tightly coupled layout engine and browser.

Another point is security fixes - with QtWebEngine, you have dozens (hundreds?) of people working on Chromium (and many dedicated to security) at Google, a handful of people cherry-picking those fixes to QtWebEngine, and another handful of people for each distribution to be sure to get them out to users.

You don't have any of that when you fork a rendering engine specifically for Otter. It's just not feasible, much less so for a very small team of developers.

As for QtMozEmbed, as far as I'm aware it was primarely done for Sailfish OS, i.e. on  mobile devices. I'm pretty sure adapting that to work with a desktop browser is going to be a lot of work as well.

Both @Emdek and I (for my [own Qt-based browser](http://www.qutebrowser.org/)) have of course looked at alternatives. There aren't any feasible ones we're aware of. ([Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef) is pretty much the only feasible, well-maintained alternative - but yeah... :wink:)

**Comment by Emdek** [comment]
@wblgrh, Qt 5.6 most likely will stop producing binaries for QtWebKit so in case of Windows it might happen quite soon (especially since QtWebKit is quite buggy under that platform...).
I'll make final decision between beta and RC of Qt 5.6.

@LimboSlam, Gecko is most likely dead end anyway, probably (although they don't admit it) Mozilla will switch to Servo sooner or later. 
Killing off stuff like XUL might be additional hint of such possibility, as it will make it easier to move to different engine in future (more like long term, maybe even more than one year from now).
As noted by @The-Compiler, that engine was not designed to be reusable, there were many Gecko based browsers in the past but almost all of them were just more or less modified versions of Firefox or SeaMonkey anyway.

**Comment by wblgrh** [comment]
@The-Compiler, You're talking about security and yet, without hesitation you've accepted a web engine from a megacorp which is infamous for spying on it's users and ignoring their right. If i have to choose between this and an unmaintained, but google free engine, then it's no contest.

@Emdek, Qt bindings for Gecko don't work under windows, QtWebKit is quite buggy under windows, windows, windows, windows...
It's not the only existing platform and yet, because of the issues of windows, every platform should get the same punishment?

**Comment by LimboSlam** [comment]
@Emdek and @The-Compiler: The Pale Moon browser is a fork of the old Gecko source code because they don't and will not go with Mozilla's directions of Firefox, so knowing this, "Pale Moon is not Firefox and never will be again," which is why for the fork. 

I also don't understand why you can't base your browser off this engine and ride it's waves? I mean that's what the Pale Moon developers use to do with Firefox/Gecko before they decided to fork off and form their own direction? Can't you like ask for the full source code from the main developer. Or is the reason because you don't have the resources to so and don't know enough of the Gecko source code? 

Well either way, I like this browser too, so whatever your doing to keep it running smoothly, keep it up! :+1:   :)

**Comment by GungnirInd** [comment]
@LimboSlam If I'm not horribly mistaken, Pale Moon isn't a browser, built from scratch, that happens to use Gecko (like Otter is to QtWebKit); it's a fork of Firefox in its entirety.  As was noted previously, Gecko was not designed to be portable, so Otter would pretty much have to be remade from scratch (and probably changed to be a Firefox or SeaMonkey fork) to make using Gecko in any way feasible.  Blink is basically the only option right now, unless Otter suddenly gets an enormous amount of developer power.  

If there's a choice between QtWebEngine and CEF, I would cast my non-existent vote for CEF (as it would make it easier to use Servo later, AFAIK), but I'd imagine that QtWebEngine is easier to work with.

**Comment by xploSEoF** [comment]
@wblgrh Otter's mantra is simple: "controlled by the user, not vice versa". It's way past the point of switching from QT, and the only engine supported enough to meet this mantra is Blink. Furthermore, Blink is NOT solely developed by Google - in fact, Google only contribute to Blink. Your google-phobia might be pushing you too far. I might add, I'm not a fan of what Google have become, neither am I a fan of Blink, but for very different reasons. 

@Emdek Keep up the good work, I trust your judgement as stability is the foundation towards a good piece of software, and you're doing a fantastic job with that!

**Comment by wblgrh** [comment]
If Otter is a browser which is "controlled by the user, not vice versa", then why a webengine which is made by a megacorp who aims to control everything? I have google-phobia? Yes i have. Is it paranoid? Yes it is. Is it unfounded? Not it isn't, it's righteous.

As for your statement of "Google only contribute to Blink", i have to concur: Blink is a fork of WebKit, which was done by google. It's true, that anyone can contribute to Blink, but ultimately google controls that engine's development and behaviour. It's up to you, if you trust them, or not. I don't trust them, not even for a yottosecond.

You can call me a paranoid google-hater and you will be right, but as i already said earlier "being paranoid does not excluse the possibility of being persecuted".
I don't hate microsoft or google, because i don't like their faces...

**Comment by Chocimier** [comment]
>  webengine which is made by a megacorp who aims to control everything
@wblgrh: Please show us QtWebEngine code fragment which controls you or  
stop talking gibberish and get out of here.

**Comment by Emdek** [comment]
@wblgrh, I'm not going to drop QtWebKit as long as there is some kind of upstream support for it.
Note that even if it would be disabled by default or something like that then it can be always built from source or that backend could be even maintained by third party.
It's not punishment, it's pragmatism, since QtWebKit is broken and almost unmaintained then we need to focus on something else...
BTW, there will be disclaimer in docs of QtWebEngine stating that they won't ship any Chrome specific code.

@GungnirInd, CEF is also an option, but indeed harder one, although since Servo is supposed to be CEF compatible then it would make sense to at least research it a bit.

**Comment by LimboSlam** [comment]
@wblgrh: What @Emdek is trying to say is that they need to more on to a more stable web engine because QtWebEngine is becoming unstable and is quite broken already due to lack of support for it. Which is how the Chromium source code/web engine fits in. Now this not a bad idea all the way, it's just more limited in what you can do with it. Now I seen great projects move to this and still manage to do more with Chromium than what they could do before. Look at Vivaldi for an example. 

Also @GungnirInd: Not quite I understand you. Um, Yes Pale Moon is not totally built from it's own source code, it had help of Gecko/Firefox source code. But now they've jumped off the Firefox train of distinction and are doing pretty well with maintaining it as their own independent fork.

By the way, what is CEF? Sorry if it's obvious, but I've just barley been introduce to Otter and it's project.

**Comment by GungnirInd** [comment]
Sorry @LimboSlam, I didn't phrase that very well.  What I mean is: the reason Gecko isn't feasible is that Mozilla never really intended for it to be used in other browsers, so it would be a huge amount of work to adapt it to Otter (or adapt Otter to it).  Blink has much better support for being used by browsers other than the one it was made for, so using it makes much more sense for a new project (which is why so many browsers are using it these days: Opera (Next), Vivaldi, Maelstrom, Iron, Steam's browser, etc., and even non-browser projects like GitHub's Electron Shell).

Pale Moon doesn't have to deal with this problem because it's based on Firefox, so the program's architecture is compatible and the implementation is already done.  They diverged from the original source they forked, but they are still using the same basic architecture as Firefox.  I agree that having support for Gecko, at least as an option, would be nice, but I don't think it'd be worth the effort.

CEF is the Chromium Embedded Framework; it's a framework for embedding browser functionality via Chromium/Blink.  Wikipedia does a much better job of explaining than I could: http://en.wikipedia.org/wiki/Chromium_Embedded_Framework

**Comment by wblgrh** [comment]
@Chocimier, Me talking gibberish? Read again what you quoted, please. I said, they *aim* to control everything, why they would make an exception with Blink?
Also i told earlier, that there is no evidence about Blink being harmful, but there is no evidence for the opposite either; it's about being careful.
So, it's you who talking gibberish, but it's not a surprise from someone who cannot read even an one-lined quote.

But since, it's your project, be as your wish, i'm leaving. Be happy. Google is watching you.

**Comment by LimboSlam** [comment]
@GungnirInd: Thanks for clearing that up and the helpful link. So does Otter have plans for CEF3 since CEF1 and 2 is dead.

**Comment by xploSEoF** [comment]
@wblgrh please check your "facts" before posting statements such as "Blink is a fork of WebKit, which was done by google" - it wasn't, and if it were, you realise you're argueing for continued use of Webkit?! Webkit was (and still is) open source, built on KDE libraries. You're fighting a battle with direction, evidence or realism - take a step back and reassess what you're doing. Don't make more statements without sources that can't be verified with a quick search (oh the irony, most people will search via Google). Most importantly, please calm down.

If you feel what you're saying is falling on deaf ears, perhaps it's not the ears that are deaf, but the words are actually just white noise that blends into the background. Repeating oneself and expecting a different outcome is rather insane, so perhaps once QtWebKit is no longer supported, Otter will no longer be a browser for you.

@Emdek Perhaps it's time to lock out this "issue"?

**Comment by wblgrh** [comment]
> "Blink is a fork of WebKit, which was done by google" - it wasn't

https://en.wikipedia.org/wiki/Blink_(web_engine)
> It is a fork of the WebCore component of WebKit

It wasn't, you say?

> you realise you're argueing for continued use of Webkit?!

No. I arguing aganist something which is now controlled by google.

> Webkit was (and still is) open source, built on KDE libraries.

I know what is KHTML, but i don't know how this related here.

> If you feel what you're saying is falling on deaf ears, perhaps it's not the ears that are deaf, but the > words are actually just white noise that blends into the background.

Or maybe it's not white noise, you just cannot interpret the meaning.

> perhaps once QtWebKit is no longer supported, Otter will no longer be a browser for you.

Yes. This is what i was afraid of.

But this was my last message, for i got only false statements or hate messages/personal attacks in response, (and they say, i should calm down; do you think that "gibberish talk" or "get out of here" is a polite and calm way of communicating?); i've bet, that there will be a response like "why did you came back"...

I just wanted to bring the attention to a possible danger, but if nobody care, then neither i won't.

**Comment by francoism90** [comment]
The adblocker doesn't work when using qtwebengine as backend.
Hope you guys can port it. :)

**Comment by Emdek** [comment]
@francoism90, that will be possible (at least partially) after updating to Qt 5.6 (should be release soon).

**Comment by francoism90** [comment]
@Emdek OK, thanks for the info. (Y)
Keep up the good work. :)

**Comment by VSHY** [comment]
Qt 5.6 <a href="http://wiki.qt.io/Qt-5.6-release">should be realised today</a> :)

**Comment by Emdek** [comment]
We already exposed almost everything that could be exposed with current APIs provided by QtWebEngine.
