### ISSUE TITLE
Customizable context menus (JSON file)

### ISSUE THREAD

**Issue by landroni** [OtterBrowser/otter-browser#65]
As in Opera12, right-click on anywhere on a page and you can access 'Copy Address'. I always thought that this item was misplaced, and would be more appropriate if included in the context menu that you access when doing right-click on that tab. 

What do you think?

**Comment by ersi-dnd** [comment]
Sorry about yet another duplicate :)

In Opera they were all normal menus which I saw as an advantage. For example IE and FF et al. have made the effort to make the items in bookmarks menu right-clickable, aand Otter has the same thing now too. For me, the right-click properly belonged to bookmarks manager and bookmarks toolbar, not to bookmarks menu.

The problem is consistency - if one menu, such as bookmarks menu, is right-clickable, why not other menus, such as Tabs menu or History list or any other menu item?

**Comment by Frenzie** [comment]
@ersi-dnd 
> The problem is consistency - if one menu, such as bookmarks menu, is right-clickable, why not other menus, such as Tabs menu or History list or any other menu item?

On the flipside, I don't think any of them allow you to use modifiers like Shift and Ctrl on the menu while Opera does. Otter merely adds an extra way of accessing that functionality.

**Comment by Emdek** [comment]
@ersi-dnd, need for yet another special case for alternate stylesheets menu was the last straw, it motivated me to take care of #42. ;-)
So we could let scriptlets to get modifiers and other stuff so they would decide what to do themselves.

The only missing part is nice way to generate entire menus using that concept, trying to combine power of C++ and flexibility of JS without defining everything in JS (which would be bad *bad*, especially in our case).

Anyway, we already try to take modifiers and button into account everywhere where it makes sense right now, see:
https://github.com/Emdek/otter/blob/master/src/core/WindowsManager.cpp#L761

BTW, hints (as set of flags instead of few, inconsistent and non-flexible bool variables) are based on idea by @bajasoft.

**Comment by Chocimier** [comment]
During implementing this function I've changed custom main and button menu location.
If you have customized this menus, please move files menuBar.json and menuButton.json (if you have them) from main Otter's configuration directory to menu/ subdirectory.
Thank you for your understanding.

**Comment by Emdek** [comment]
Also note that subactions are still planned, probably they will get own ticket later.
