### ISSUE TITLE
add startpage search engine by default

### ISSUE THREAD

**Issue by landroni** [OtterBrowser/otter-browser#679]
At the moment I'm only aware of two privacy-aware search engines: DDG and [StartPage](https://en.wikipedia.org/wiki/Ixquick#Startpage.com). startpage.com is also being used by default in the Tor Browser. SP will send the search query to and fetch results from the Google search engine, crucially without saving the users' IP addresses or giving any personal user information to Google's servers. 

Please consider including SP in the list of default search engines.

**Comment by resbro** [comment]
You can put it there yourself. Go to Startpage and right click in the searchbox then click on Create Search... DONE ! Make it default if you want to. or any other one you like.

**Comment by landroni** [comment]
Sure, I can do that for Google and DDG, too... But Otter still ships them by default. One because all use it, and the other because it respects privacy and yields decent results. By the same token, I think SP should be shipped by default, because it combines the world's most used search engine with privacy.

**Comment by ersi-dnd** [comment]
I don't know what a privacy-aware search engine is these days. DDG displays results the same way as Google: Instead of clean links to the results, it redirects them through their own cache or something. Try this:

1. Search something in DDG
2. Hover above a result to take a look at the url
3. Click on it and observe the address field

It does not go straightforwardly to the url. It goes through some cache. It's not as bad as in Google, but bad enough. 

In Google when you hover on search results, you see the "right" url, but when you right-click and copy the url, you will get something totally different on clipboard. Browsers should see through deception like this. Browsers should inform the actual url. I don't know why Google is allowed to deceive people like this.

**Comment by landroni** [comment]
Yes, I also noticed the redirects from DDG. I'm not sure how much of an issue these are for privacy, though. What they *say* is that they do not collect IP addresses, and that two searches cannot be linked. Unlike Google, for instance, who create profiles on IP addresses. 

If you search with SP: 
https://startpage.com/

and you hover, click on a link, or right-click and copy it, the link shall go through no redirect...

**Comment by Emdek** [comment]
Do they have readily available file in this format?
http://en.wikipedia.org/wiki/OpenSearch

I don't see a problem to add them. :-)

**Comment by landroni** [comment]
Hmm, I'm not sure. I did a quick search, but couldn't find anything relevant...

**Comment by landroni** [comment]
The redirect seems to be used by DDG to improve privacy: 
http://webapps.stackexchange.com/questions/73312/are-duckduckgo-redirects-a-privacy-issue

**Comment by Emdek** [comment]
Fixed in 0aaebcf9b48e3896726342da7e7e2ff170203cc9.
