### ISSUE TITLE
Add some sort of border on bottom of top panel

### ISSUE THREAD

**Issue by MazheM** [OtterBrowser/otter-browser#681]
On some sites background of top block have same color as Otter top panel and its
looks like a continuation of the browser. For example: http://habrahabr.ru/
![Same colors](https://cloud.githubusercontent.com/assets/5282790/5966111/9300a814-a812-11e4-8fd2-e04c31216a31.png)

**Comment by Emdek** [comment]
Yep, we need to do something with that, also borders of find bar or permissions bar...
Although it will be hard to do it properly once, so it will look good under all platforms, without adding extra styles. :-/

**Comment by Felipefpl** [comment]
"Although it will be hard to do it properly once, so it will look good under all platforms, without adding extra styles. :-/"

I was wondering how hard would be to make rounded tabs like on opera 12 but it seems you got enough problems already. :P

Do you really wanna make this from the beginning? Why not just look at how the other browsers like firefox did it? Or is it something different?

**Comment by Emdek** [comment]
@Felipefpl, that is a bit different thing, see #36.

**Comment by pierreporte** [comment]
I was wondering, with about:something pages, the borders already exist as we want, right? It’s because these are widget-pages, which have a border-style like “sunken”. However, the webview doesn’t have such style, thus there is no border with web pages. Hence, would it be possible to either add a border style to webview widgets or to put all pages in a frame (that has a border style) and use this frame as a container to frameless widget-pages and frameless webviews?

**Comment by Emdek** [comment]
@pierreporte, yes and no, without extra effort it will clip content in corners (slightly but still) and add borders on edges that do not need it (left and right by default).
Safari clips bottom corners since OS X windows use rounded corners and it may lead to sort of data loss if something important but (very) small will end up in one of these corners. ;-)

**Comment by pierreporte** [comment]
If the extra effort to avoid clipping is worth it, since Qt widgets understand CSS for styling, can we just disable unwanted borders? Let’s say the default border width is 1. By default, we would have

    widget {
        border-top: 1;
        border-left: 0;
        border-right: 0;
        border-bottom: 1;
    }

and when we want do display a side panel, we just apply the rule `border-left: 1`. When the user wants to hide it, `border-left: 0` is applied and so on.

**Comment by Emdek** [comment]
@pierreporte, they understand and also suffer from abusing it (performance degradation, sometimes really visible). ;-)

**Comment by Emdek** [comment]
I guess that it would be best to go for `QStyleOptionToolBar`, since it's used by other toolbars (so it will be consistent), we just need to setup it so `QStyle` will know toolbar positions (the most important information is which one is the last one).

**Comment by pierreporte** [comment]
Shouldn’t this be also applied to the status bar and side panels?

**Comment by Emdek** [comment]
@pierreporte, don't ask me about bogus styles that ignore hints. :-P
I'm working on a way to force border (mostly for Windows, since there it's totally random but predictable) but I'm not convinced that it should be simply on for all styles since some are sane.
