### ISSUE TITLE
Panel-switching toolbar has disappeared

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#683]
A regression: The toolbar with buttons to switch the panels (bookmarks, history, transfers) has disappeared.

And a request: Opera had an option to switch the panel from a menu too. The user was able to choose between the toolbar or the menu. I preferred the menu.

And in Opera there was also ability to set a unique keybind for each panel separately.

**Comment by Emdek** [comment]
Hopefully we will be able to finally pull in rewrite done by @Chocimier for weekly `#58`, it needs just a little cleanup.
Note that this change will break (at least for some time, until we will find a better solution) ability to drag it around, but will introduce a secondary sidebar, so while it won't be win-win solution it will still give some new possibilities (16:9 displays tend to waste horizontal space, having option to show sidebars on both edges should allow some wild configurations).
We decided to do it that way due to numerous issues with ``QDockWidget`` approach, like QtWebKit crashes while detaching sidebar containing panel based on web content etc.
Shortcuts to select panels were already considered, but this will need some other changes and good design to dynamically generate actions (although you can except some interesting changes **soon**, go to our IRC channel for details ;-)).
