### ISSUE TITLE
Crashes on refreshing

### ISSUE THREAD

**Issue by Stullemon** [OtterBrowser/otter-browser#703]
Hi, I noticed that Otter crashes somewhat frequently, if I reload some websites. It does not happen all of the time but in, say, more than 10% of the reloads of the website mangastream.com it happens with all of my recent upstream builds on Linux Mint 17.1.

The crash usually happens when I am trying to figure out, if any new releases have been published on mangapanda.com and mangastream.com. Most of the time it happens I am switching from a third Tab to mangapanda, refresh, wait for the topmost items to be displayed, switch tabs (while mangapanda is still not finished loading) and  go to mangastream, refresh --> immediate crash.

For the sake of completeness, I have 11 tabs open, if it makes any difference.

**Comment by The-Compiler** [comment]
Unfortunately for Otter (and other QtWebKit browsers) there are some segfaults when using an old Qt version.

Linux Mint 17 is using Ubuntu Trusty as base, which is still stuck on Qt 5.2.1 - since then, [over 70 crashes](https://bugreports.qt.io/browse/QTBUG-42417?jql=component%20%3D%20WebKit%20and%20resolution%20%3D%20Done%20and%20fixVersion%20in%20(5.3.0%2C%20%225.3.0%20Alpha%22%2C%20%225.3.0%20Beta1%22%2C%20%225.3.0%20RC1%22%2C%205.3.1%2C%205.3.2%2C%205.4.0%2C%20%225.4.0%20Alpha%22%2C%20%225.4.0%20Beta%22%2C%20%225.4.0%20RC%22)%20and%20priority%20in%20(%22P2%3A%20Important%22%2C%20%22P1%3A%20Critical%22%2C%20%22P0%3A%20Blocker%22)) in QtWebKit have been fixed.

Unfortunately the only thing you can do is to wait for the next update of Linux Mint probably :-/

**Comment by Stullemon** [comment]
Hi, that's some interesting information. I was trying to get QT 5.4 to work the other day but - being a Windows user myself - I failed miserably. It would be nice to get a somewhat more detailed explanation on how to compile Otter with a custom install of QT 5.4. The current one is somewhat vague and I just end up with build errors...

**Comment by ersi-dnd** [comment]
Arch and its derivations have very recent software in the repos - bleeding edge when you switch to unstable branch. Perhaps there are other distros that do similarly. Debian-based distros are left behind in this area.

**Comment by Emdek** [comment]
@Stullemon, you can use Qt SDK, there is high chance that it will work out of the box:
http://www.qt.io/download-open-source/
