### ISSUE TITLE
Separate visibility settings for toolbars in full screen mode

### ISSUE THREAD

**Issue by Emdek** [OtterBrowser/otter-browser#764]
Currently there is only generic visibility setting that affects both normal and full screen modes, with addition in form of tab bar being shown when mouse cursor moves to the edge where it was placed (as long as it is set to being visible).

We can add separate *fullScreenVisibility* attribute to allow to decide if toolbar should be always visible, visible only when mouse cursor is near its edge or always hidden.

There are no plans for separate option to set toolbar location in full screen mode.

Related issue: #364.

**Comment by lollox** [comment]
About the tabbar in full screen mode, it could be interesting having also:

- an **option** (so no one will have problem with it) to use the Visual tabs instead of the normal tabs (in fullscreen this would be a lot more convenient since there's more space and the tabbar is visible only on hover)

- change the current behavior in which when you move the cursor to the edge and the tabbar is showed, the Webkit area shift away, to an "overlay" behavior in which the tabbar simply covers the Webkit area .... I think it's a lot more pleasant

**Comment by Emdek** [comment]
@lollox, such option is doable, although it would complicate stuff, it belongs to #190, as it would be an option for ``TabBarWidget`` itself.

The latter idea could be done as global switch, since allowing to set it separately per toolbar doesn't make much sense (I doubt that anyone would like separate modes anyway, more like user would be annoyed by having to set it separately if allowing more than one toolbar to be set to "auto hide"), so it would be a global option only.
There is one issue, combining "always visible" and "auto hide" toolbars with the same location (top, bottom, left, right) might result in ignoring option to overlay them (as it would require duplicating parent widget and use complicated reparenting and positioning, way to easy to break in more complicated cases).

**Comment by lollox** [comment]
Just a clarification: If I understood correctly, the problem is that if for example you put the cursor on top edge that could be (based on user' preferences) the trigger point for both tabbar and main toolbar... but the same problem doesn't arise with the current behavior too? What I proposed is changing only the way that toolbars will look (simply hover the webkit aread instead of shifting it) but how they are "called" from the user shouldn't change.

About the first point I wrote it because I thought the visual tabs were yet on the roadmap (so I simply proposed a separate option for fullscreen mode)... If they are not, well, just forget about that request :P

**Comment by Emdek** [comment]
@lollox, the issue is that we can't have overlay if one of toolbars is set to be shown as overlay and another is not and both are set to "auto hide".

Thumbnails are even in official TODO. ;-)

**Comment by ersi-dnd** [comment]
@lollox 
By visual tabs you mean the previews/thumbnails of the tabs content? 

The way I switch tabs in fullscreen is to Ctrl+Tab between them. This shows previews and all that. Opera also used to have Right-click+scroll for the exact same thing. (As with all keybinds, these should be configurable.)

**Comment by lollox** [comment]
I mean using Otter in fullscreen should be (to me) an experience quite similar to this: http://winsupersite.com/content/content/142567/ie10metro_05.jpg

for example put the cursor on top edge and your tabs are showed with thumbnails.... In this concept I've still lot of interesting ideas but I can't ask @emdek to follow my vision :P

**Comment by Emdek** [comment]
I'll consider option to allow toolbars to cover widget in future, perhaps while working on #1086, where panel might gain an option to float over content (for example when only hovering buttons while no panel is shown).
