### ISSUE TITLE
"Transfer" and similar strings in english localization. Why not change to "Download" and similar?

### ISSUE THREAD

**Issue by Piter432** [OtterBrowser/otter-browser#776]
As title says. Currently the english localization of Otter has download manager, but it's called "Transfer/s". Why not change to "Download/s"? In Polish localization it's called "Pobrane", etc. What do you think about that @Emdek? :)

**Comment by komoku** [comment]
IIRC, Opera traditionally called them "Transfers" (maybe because with bittorrent support it could also upload?), although at some point they got renamed to the equivalent of "Downloads" at least in the Spanish localization, don't know about the English one.

Case in point anyway: "Transfers" may be adequate if support for uploads is planned. If not, probably "downloads" would be simpler.

**Comment by uahim** [comment]
it's only cosmetics, but I'm with Piter432
