### ISSUE TITLE
We need cert manager to import self-signed cert or about:config key to completely ignore cert error

### ISSUE THREAD

**Issue by cattleyavns** [OtterBrowser/otter-browser#872]
Issue:

'''
SSL errors occured, do you want to continue?
The issuer certificate of a locally looked up certificate could not be found
No certificates could be verified
'''

When visiting website using self-signed certificate or for people using web filtering proxy with SSL support like Proxydomo (https://github.com/amate/Proxydomo)

So we need a Cert manager interface or a about:config key to auto ignore cert error or at least a secret way to import self-signed certificate.

**Comment by Felipefpl** [comment]
Msgs pestering us about certificates are one if not the most annoying thing of Opera 12 too, i'm having problems to see avatars from gravatar on it because i cant click on approve unless i turn off OCSP then i can approve or reject the certificates that opera 12 doesnt get, the best way to solve this is let the browser choose one certificate automatically just like you can do on firefox if you select this option.

**Comment by pmattern** [comment]
Something similar is already addressed in #550.
