### ISSUE TITLE
handling of incorrect encoding 

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#916]
Hi, on some occations I noticed some problems in manual handling of encoding of webpages.
Everything works ok if a page has correctly specified encoding; if there is no declaration or the respecive item is invalid, it is still possible to set it manually via page menu.
However, if a declaration is formally ok, but incorrect, I am not able to override it via manual setting.
could this possibility be supported too?
This is also connected with the source viewer - could this view use the current encoding setting of the page (be it taken from page source or manual setting)? - It appears, it currently falls back to win-1252 on windows, if there is no valid declaration.
(using Otter 0.9.07 weekly 84 webkit on win 7)
Thanks for considering this and for continued enhancements.
regards
   vbr

**Comment by Emdek** [comment]
I'm afraid that we can't do more than is available currently, we are using the only available way but WebKit simply thinks that it knows better and overrides it. :-/
I might prepare a test case to verify that, but since it is deprecated upstream it unlikely that it would get fixed...

Using character set manually set for page is indeed a good idea, passing it as hint for source viewer would help in such situations as in that case we have full control over it.
I guess that fallback encoding depends on platform and locale, we are using ``QTextCodec::codecForHtml()`` if Content Type header is invalid.

**Comment by vbr** [comment]
Thanks for the clarification, if it is an upstream problem of the component, it migh be tricky to handle. 
If source viewer could reflect the manual setting somehow,, it would probably solve most of the problem (in connection with the old Opera's "reload from cache" mentioned some time ago, the viewing of badly encoded pages would be handled almost completly).
Another potential quirk is, that the menu checkbox in the list of the settable codepages remains selected, even if it doesn't correspond with the displayed page.
But it is clear, that it is a kind of cornercase for general usage.
regards,
    vbr
