### ISSUE TITLE
Toolbar Spacing Doesn't Look Right

### ISSUE THREAD

**Issue by opticyclic** [OtterBrowser/otter-browser#936]
There are 2 issues here to do with the spacing on the toolbar.

1) As per the second issue here https://github.com/OtterBrowser/otter-browser/issues/82 the address bar and search field are not the same size.

It is mentioned that it is a theme issue (not sure I agree) but if it is, the default theme should make them the same size!

2) The space between the tab bar, toolbar and web page flow into each other too much making it hard to see where one ends and another starts and it looks like a massive gap between the bottom of the  tabs and the top of the address bar.
This was clearer in Opera although Vivaldi is even more explicit with coloured boxing..

Otter
![otter](https://cloud.githubusercontent.com/assets/1222693/9752205/80d2b228-567b-11e5-8491-b5b2264ad68f.PNG)

Vivaldi
![vivaldi](https://cloud.githubusercontent.com/assets/1222693/9752206/8f83fa84-567b-11e5-8842-e2f9dba44558.PNG)

**Comment by uahim** [comment]
this a) is just cosmetics and b) a matter of taste. personally I find Vivaldi's gui awful (and I won't even mention its non-nativeness)

**Comment by opticyclic** [comment]
#82 is now closed and the most obvious UI issue still remains.
The search box and the address bar are not the same size.

**Comment by Emdek** [comment]
@opticyclic, well, that sizing issue doesn't make any sense for me, they use same settings for delegate etc. but somehow they differ with some styles (works fine for me with Fusion). :-/

**Comment by opticyclic** [comment]
What is Fusion? A theme?
Can you post a screenshot with the default theme and with Fusion?

**Comment by mytskine** [comment]
I don't know if the address bar and the search box should have the same size, but their sizes are indeed very unequal. The writable space in the latter is about 15 characters wide, one tenth of the former.
Here is the result on a 1920x1080 screen with no desktop manager:
![otter-addressbar](https://cloud.githubusercontent.com/assets/516560/19159490/014b951c-8bed-11e6-8013-fb5820f664ec.png)

**Comment by Emdek** [comment]
Tab bar draws line on the bottom of the toolbar for some time already, so this one is fixed.
But native Windows 10 style simply doesn't provide extra decoration for toolbars, so that part won't change there without custom style.
The only remaining issue is that height issue when comparing address field ans search field, which doesn't make sense from programming point of view since both use the same styling internally (both use the same widget type and almost identical delegate to draw items). :-/

![screenshot_20170124_213805](https://cloud.githubusercontent.com/assets/1078195/22624506/c755d4f8-eb7d-11e6-9f0f-04c3e5abcc98.png)

**Comment by Emdek** [comment]
Remaining part of this issue found new home here: #1073.
