### ISSUE TITLE
Paste&Go at Tabbar midclick

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#958]
In Opera there's an option to Paste&Go when the user midclicks Tabbar on empty space (not on a tab item) opera:config#UserPrefs|PageBarOpenURLOnMiddleClick

I think it makes sense to provide the same function for the New Tab button: When the user midclicks new tab button, the browser does Paste&Go.

In Opera this is an option, i.e. can be on or off.

**Comment by Emdek** [comment]
@ersi-dnd, we will allow to use such stuff by defining mouse gestures, as part of #77.

**Comment by FeyFre** [comment]
My $0.02

*This is my opinion based on mine POV, experience and assumption project aimed to recreate original Opera's behaviour.
**Short conclusion if lazy to read: it is unlikely it should be implemented as Mouse Gesture, and there is must be easy-to-use way to turn it off/on.

The Question: is it possible to setup build-process to make defaults(in our case Mouse Gestures) are target-platform dependent?
Why it matters(for me)? Well:

1. This particular behaviour is not what Opera invented or ever presented it as outstanding feature(afair). As far as I know and Ruarí Ødegaard(cheerful Opera's employee) can probably confirm it(if he remember our discussion) it: this feature was made as implementation of well-expected behaviour on *nix platform: default action for middle click in X Windows - paste text from clipboard. So in summary Opera got action "create tab - paste text from keyboard URL - go" action bound to middle click on address bar. And that was never implemented as Mouse Gesture.

2. IMPORTANT: This particular behaviour is native and expected only for XWindow platform, so users who whole life spent(and got used to it) on Windows platform(like me) never expect such behaviour. More over, it annoys US when on Linux we middle click on bar and got instantly navigated... well you know, it annoys very much. There are a lot of US(those who migrated from Windows to Linux). That why option which controls this behaviour opera:config#UserPrefs|PageBarOpenURLOnMiddleClick has different default values on different platforms(Linux - on, Window - off), AND user can easily change it(i.e. it is no hardcoded behaviour). First thing I do during first Opera run on Linux platform - turn it OFF.

3. MOREOVER: It is well known security breach. Guess, what will happen if clipboard contains sensitive information(password, credit ID, etc). User middle clicks address bar(and pretty possible unintentionally, just misses tab) - sensitive data instantly posted into default search engine(i.e. got published - compromised). Thats why it is very important to give user option to turn this feature off(if impossible to get rid it).

So my conclusions:
1) Because of 1, 2: this feature past be activated/inactive by default dependently of platform application runs. If Mouse Gestures defaults can be set up differently for each platform - I agree it to be implemented as Mouse Gesture. 
2) Because of 2, 3: feature cannot have hardcoded state(OFF/ON), must be easy-to-deactivate, regardless of active Mouse Gesture profile.

Welcome to discuss.

**Comment by Emdek** [comment]
@FeyFre, yes, that is planned from beginning, but so far we only have meta profile and nothing more yet.
https://github.com/OtterBrowser/otter-browser/blob/master/resources/keyboard/platform.ini
