### ISSUE TITLE
Text selection problem

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#971]
While selecting text you will not see text being highlighted until you release the mouse click.

**Comment by pmattern** [comment]
Problem seems to be related to the web backend somehow: I can confirm the finding with latest VCS checkout compiled against QtWebKit from Qt 5.5.1 on Arch Linux but not with QtWebEngine under otherwise identical conditions.

@beastie1 
Besides not a developer I dare say you should provide some information about the OS you're using, Otter version and the likes.

**Comment by Emdek** [comment]
It's regression introduced while working on #77.
