### ISSUE TITLE
Use consistent identifiers for languages

### ISSUE THREAD

**Issue by glixx** [OtterBrowser/otter-browser#985]
GenericName[ru_RU]=Веб-браузер
is wrong
should be
GenericName[ru]=Веб-браузер

The same problem for other languages.

**Comment by Emdek** [comment]
@glixx, it all depends on which exactly identifier got requested by translators:
https://www.transifex.com/otter-browser/otter-browser/

I'm not sure if we can do anything about that.

**Comment by glixx** [comment]
lang for desktop file <> lang for ts file.
you can use lang from desktop file for ts files ([ru] -> ru.ts) or to create new project on transifex for translation desktop file.

**Comment by Emdek** [comment]
@glixx, after contacting their support and getting reply ("no, we do not allow to change identifier of language of existing translation") @aurhat found a way to migrate most of metadata which will allow us to "rename" them by creating new translations and importing there data from existing ones.
Migration is planned for tomorrow.

**Comment by glixx** [comment]
@Emdek, yes, I saw your announcement on transifex. You go by the right way.

**Comment by pejakm** [comment]
I also need to point out that Ijekavian variant identifier for Serbian is incorrect on Transifex. It should be sr@**ijekavian** instead of sr@**Ijekavian** (notice the capital "I"). I have reported this to Transifex support over a year and a half ago, they said they are "working on this". I gave all my hope that they will actually fix it some day, so I do not intend to send them emails again.
What can be done from a user perspective, is to manually rename files/strings. For otter this should be done:

- [ ] rename `resources/translations/otter-browser_sr@Ijekavian.ts` to `resources/translations/otter-browser_sr@ijekavian.ts`
- [ ] change occurrences of `@Ijekavian` to `@ijekavian` in `otter-browser.desktop` file

**Comment by pejakm** [comment]
Or simply change the translation platform, switch to something else (for example Weblate, it is FLOSS and free for FLOSS projects).

**Comment by Emdek** [comment]
@pejakm, I've considered changing platform, but right now that would be a bit too big effort to undertake...
We have many translators and I guess that not all of them would welcome such change. :-/

**Comment by comradekingu** [comment]
@Emdek I stopped using Transifex after their new EU-GDPR EULA went up, and I would have to accept it to even log in. Is now a better time to move?
